### ISSUE TITLE
非循环模式下，从最后一个item慢慢向上滚，初始显示不对。会先向下然后不断抖动

### ISSUE THREAD

**Issue by muyongyin** [Bigkoo/Android-PickerView#117]

**Comment by pihat** [comment]
显示不对是什么意思？
项目里用到这个控件，对于抖动问题，我是在WheelView里的onTouchEvent里的Move事件修改
`
if (totalScrollY - itemHeight * 0.3 < top) { top = totalScrollY - dy; } else if (totalScrollY + itemHeight * 0.3 > bottom) { bottom = totalScrollY - dy; }
`
把这段代码注释掉了，目前使用没问题，如果会新增bug，欢迎反馈
