### ISSUE TITLE
使用的时候发现的崩溃，作者有空的时候看看

### ISSUE THREAD

**Issue by coasterleung** [Bigkoo/Android-PickerView#121]
#1 main

java.lang.ClassCastException
java.lang.String cannot be cast to java.lang.Integer
解析原始
}
1 com.bigkoo.pickerview.adapter.NumericWheelAdapter.int indexOf(java.lang.Object)(NumericWheelAdapter.java:52)
2 com.bigkoo.pickerview.lib.WheelView.void onDraw(android.graphics.Canvas)(WheelView.java:412)
3 android.view.View.draw(View.java:15352)
4 android.view.View.buildDrawingCacheImpl(View.java:14598)
5 android.view.View.buildDrawingCache(View.java:14460)
6 android.view.View.updateDisplayListIfDirty(View.java:14269)
7 android.view.View.getDisplayList(View.java:14310)
8 android.view.View.draw(View.java:15080)
9 android.view.ViewGroup.drawChild(ViewGroup.java:3409)
10 android.view.ViewGroup.dispatchDraw(ViewGroup.java:3202)
11 android.view.View.draw(View.java:15355)
12 android.view.View.updateDisplayListIfDirty(View.java:14288)
13 android.view.View.getDisplayList(View.java:14310)
14 android.view.View.draw(View.java:15080)
15 android.view.ViewGroup.drawChild(ViewGroup.java:3409)
16 android.view.ViewGroup.dispatchDraw(ViewGroup.java:3202)
17 android.view.View.updateDisplayListIfDirty(View.java:14283)
18 android.view.View.getDisplayList(View.java:14310)
19 android.view.View.draw(View.java:15080)
20 android.view.ViewGroup.drawChild(ViewGroup.java:3409)
21 android.view.ViewGroup.dispatchDraw(ViewGroup.java:3202)
22 android.view.View.draw(View.java:15355)
23 android.view.View.updateDisplayListIfDirty(View.java:14288)
24 android.view.View.getDisplayList(View.java:14310)
25 android.view.View.draw(View.java:15080)
26 android.view.ViewGroup.drawChild(ViewGroup.java:3409)
27 android.view.ViewGroup.dispatchDraw(ViewGroup.java:3202)
28 android.view.View.updateDisplayListIfDirty(View.java:14283)
29 android.view.View.getDisplayList(View.java:14310)
30 android.view.View.draw(View.java:15080)
31 android.view.ViewGroup.drawChild(ViewGroup.java:3409)
32 android.view.ViewGroup.dispatchDraw(ViewGroup.java:3202)
33 android.view.View.updateDisplayListIfDirty(View.java:14283)
34 android.view.View.getDisplayList(View.java:14310)
35 android.view.View.draw(View.java:15080)
36 android.view.ViewGroup.drawChild(ViewGroup.java:3409)
37 android.view.ViewGroup.dispatchDraw(ViewGroup.java:3202)
38 android.view.View.draw(View.java:15355)
39 android.widget.FrameLayout.draw(FrameLayout.java:598)
40 com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2736)
41 android.view.View.updateDisplayListIfDirty(View.java:14288)
42 android.view.View.getDisplayList(View.java:14310)
43 android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:275)
44 android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:281)
45 android.view.ThreadedRenderer.draw(ThreadedRenderer.java:320)
46 android.view.ViewRootImpl.draw(ViewRootImpl.java:2577)
47 android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2397)
48 android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2024)
49 android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1080)
50 android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5976)
51 android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
52 android.view.Choreographer.doCallbacks(Choreographer.java:580)
53 android.view.Choreographer.doFrame(Choreographer.java:550)
54 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
55 android.os.Handler.handleCallback(Handler.java:739)
56 android.os.Handler.dispatchMessage(Handler.java:95)
57 android.os.Looper.loop(Looper.java:135)
58 android.app.ActivityThread.main(ActivityThread.java:5506)
59 java.lang.reflect.Method.invoke(Native Method)
60 java.lang.reflect.Method.invoke(Method.java:372)
61 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:952)
62 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:747)

**Comment by saiwu-bigkoo** [comment]
估计是滚到空字符串的位置，被转成数字就报错了
