### ISSUE TITLE
省市联动内存溢出

### ISSUE THREAD

**Issue by mudao** [Bigkoo/Android-PickerView#129]
滚动后停止,getLoopMappingIndex(index)会大量计算,造成内容突然增大.内存溢出.

**Comment by txadf** [comment]
@mudao 你的省市区数据放在呢，我放在本地数据库，也出现一直崩溃的情况

**Comment by mudao** [comment]
因为在onDrow()方法里面使用递归,运算量太导致OOM.需要改控件源码才可以解决问题.我需求比较紧,换了另一个控件.

**Comment by txadf** [comment]
是三级联动的么，方便分享么

**Comment by mudao** [comment]
wheelpicker这个滚动效果比较好,不要需要小小修改一下源码.它的默认宽度是通过计算文字长度来确定的

**Comment by esirong** [comment]
没有解决，也关闭了
