### ISSUE TITLE
发现一个问题，如果设置的字体大小小于20sp，那item中的字会显示不全

### ISSUE THREAD

**Issue by zr905474554** [Bigkoo/Android-PickerView#139]
发现一个问题，如果设置的字体大小小于20sp，那item中的字会显示不全，字的上部和下部会被截掉一小部分，大概1到3px的样子，但是如果字体设置的很小如12则不会，请问下这是什么问题?

**Comment by yumi0629** [comment]
@zr905474554 在wheelview的measureTextWidthHeight()方法中，int textHeight = rect.height()改成int textHeight = rect.height() + 10;强制把测量高度撑大一点，字就能绘制完整了。

**Comment by xiaosong520** [comment]
@yumi0629 依赖项目的代码怎么改？ 除了拷贝源代码到自己项目中去。

**Comment by xiaosong520** [comment]
@zr905474554 现在遇到的问题和你一样，也是自己设置了字体大小 - 18sp，结果显示不全，请问你是怎么解决的呢？
