### ISSUE TITLE
这个选择项Item字感觉好扁呀，而且可否添加选项设置在日期选择器中年月日不要固定在那里啊

### ISSUE THREAD

**Issue by xmjharry** [Bigkoo/Android-PickerView#140]

**Comment by pihat** [comment]
在WheelView类这里改一下就可以了
`//        paintCenterText.setTextScaleX(1.1F);
//        paintCenterText.setTypeface(Typeface.MONOSPACE);`

**Comment by xmjharry** [comment]
恩 把你的library copy下来修改了 顺便修改了在dialog中TimePickerView显示的问题
