### ISSUE TITLE
在popupWindow上面打开，出现在popupWindow下面

### ISSUE THREAD

**Issue by ysn003** [Bigkoo/Android-PickerView#141]
我要在打开的pupopWindow ，重打开时间选择器，但是时间选择器却出现在Activity与PopupWindow 的中间夹层里，请问如何解决，谢谢

**Comment by saiwu-bigkoo** [comment]
这个控件是依赖Activity的根View的，不能与PopupWindow共同弹出

**Comment by kanfRUI** [comment]
有无办法可以解决这个问题？我也遇到这个问题了

**Comment by li-xiansheng** [comment]
改写库，增加一个弹出方式，依赖到pop比较好，或者，直接把原来的show方法去掉
