### ISSUE TITLE
调用dismissImmediately()方法后“取消”按钮无反应

### ISSUE THREAD

**Issue by yumi0629** [Bigkoo/Android-PickerView#146]
在OnOptionsSelectListener中需要打开另一个activity，所以需要pickerView立即dismiss掉，若调用pickerView的dismissImmediately()方法后，再返回时“取消”按钮就没反应了，因为dismissing标志位变成了true（因为前一次点确定的时候自带的dismiss方法，因为我自己手动调用了dismissImmediately()，导致动画没走完dismissing标志位一直是true没改过来）。然后现在在“确定”按钮的监听里加了一句
`
if (isShowing()) {
                dismiss();
            }
`
就ok了。
不知道这么修改会不会有问题？？

**Comment by TEENSTITAN** [comment]
确实有这个问题
