### ISSUE TITLE
设置单位的时候 出现nullPointException ?

### ISSUE THREAD

**Issue by hnyer** [Bigkoo/Android-PickerView#148]
```
/**设置积分**/
private void  setPointsData(){
    options1Items.clear();
    pvOptions.setTitle("选择积分" );//这个正常
```

//        pvOptions.setLabels("分");  //为什么会null ？
        options1Items.add(String.valueOf(1)) ;
        options1Items.add(String.valueOf(5)) ;
        options1Items.add(String.valueOf(10)) ;
        options1Items.add(String.valueOf(20)) ;
        options1Items.add(String.valueOf(50)) ;
        options1Items.add(String.valueOf(100)) ;
        pvOptions.setPicker(options1Items );
    }

请问还需要设置什么吗 ？

**Comment by saiwu-bigkoo** [comment]
参考demo，是不是设置位置不对，没正式初始化。
