### ISSUE TITLE
按返回键activity之间finish了。。。。

### ISSUE THREAD

**Issue by yumi0629** [Bigkoo/Android-PickerView#150]
又发现了新坑。。。按返回键activity直接finish了。。。。
因为是直接在activity的contentView里面加pickerView的，返回键肯定是和activity一体的，每次一按返回键，activity就finish了。。。
建议给rootView加一个View.OnKeyListener()拦截一下返回键。。。。
因为给activity加onKeyDown()的话很不方便，每个activity都要设置，而且里面要判断pickerView的show状态。直接在BasePickerView的初始化中添加

```
rootView.setFocusableInTouchMode(true);
        rootView.setOnKeyListener(new View.OnKeyListener() {
            @Override
            public boolean onKey(View v, int keyCode, KeyEvent event) {
                if (keyCode == KeyEvent.KEYCODE_BACK && isShowing()) {
                    dismiss();
                    return true;
                }
                return false;
            }
        });
```

然后再在BasePickerView的show()方法中添加rootView.requestFocus();
这样就一劳永逸了。

**Comment by xiongwenzhi** [comment]
你好，这个问题处理的怎么样了啊

**Comment by xiaosong520** [comment]
已更新版本并处理问题
