### ISSUE TITLE
滚动触发事件; WheelView一些样式的设置

### ISSUE THREAD

**Issue by esmark-developer** [Bigkoo/Android-PickerView#159]
1.有没有暴露的滚动触发事件？
   看到好像只有setOnoptionsSelectListener，现在有个这样的问题，OptionsPickerView使用中，滚动第三级
   滚轮后，对应的位置会记录下来，我在滚动第二级滚轮后，第三级滚轮虽然刷新了数据，但是仍然会跳到
   刚才保留的那个位置；
   我需要做的功能是第二级滚轮滚动后第三级滚轮的位置会默认跳到0的位置；
   希望能把这个触发事件暴露出来，这样使用中可以自定义更多功能；或者给PickView添加一个属性，可以
   设置在上级滚轮滚动后，下级滚轮的位置是否重置；

2.关于WheelView的样式设置
   v2.0.8的更新中通过values文件暴露了字体大小颜色等一些属性的设置，想问下可以设置三级联动
   OptionsPickerView中每个WheelView的高度和宽度么？
   WheelView高度是计算得来的，但是在字体较小时，整体OptionsPickerView高度较小，能否通过自定义
   WheelView中dividing的高度来帮助辅助控制OptionsPickerView的高度？(高度仍然是通过计算得出)
   WheelView的宽度看起来像是平均分配的，在一些使用情况下(三级联动省市区地址选择，省、市地址较
   短，区域名称有的很长，如一些少数名族自治区)，平均分配并不能很好地体现数据，如果可以手动设置
   每级WheelView的宽度或者权重，就更好了

**Comment by esmark-developer** [comment]
@saiwu-bigkoo

**Comment by xiaosong520** [comment]
@esmark-developer 原作者已经转行不编程了，他把项目交给我接手维护了，刚更新了一下版本，欢迎提交 优化，pull request 我会合并
