### ISSUE TITLE
选项不显示的问题

### ISSUE THREAD

**Issue by xujunhe** [Bigkoo/Android-PickerView#170]
假设 我现在 有两个选项，第二项的第一组数据是空的，滑动第一项的内容，第二项的内容始终为空，希望修复一下，设置字体大小 显示样式 能不能公开方法

**Comment by xiaosong520** [comment]
作者交给我维护这个项目了，已更新版本，会持续更新优化，欢迎大家参与维护和优化，可以pull request 。
