### ISSUE TITLE
不支持在Dialog中使用

### ISSUE THREAD

**Issue by Ginsan** [Bigkoo/Android-PickerView#172]
TimePickerView初始化是不能传入dialog.getContext()，BasePickerView中有一个将context强制转换成Activity的初始化方法

**Comment by zr905474554** [comment]
@Ginsan 这个项目就是在activity上工作的，要在dialog里用要自己改... 我是把OptionsPickerViewUtil里的view取出来addView到dialog里

**Comment by xiaosong520** [comment]
后期会考虑添加这个功能
