### ISSUE TITLE
No English Documentation

### ISSUE THREAD

**Issue by bkolarov-appolica** [Bigkoo/Android-PickerView#182]
Over 3k stars and no English documentation. Please consider adding one!
Thanks from all future developers who will start using this library, because of the English Documentation!

**Comment by xiaosong520** [comment]
@bkolarov-appolica Hi ~ The author has  engaged in other occupations  at  a few months ago ~ I talked to him in private... it's true.  so we're thinking of taking over his work, please wait on.
