### ISSUE TITLE
原作者转行已经不编程了，为了不让这个开源项目荒废我会继续维护这个项目

### ISSUE THREAD

**Issue by xiaosong520** [Bigkoo/Android-PickerView#184]
原作者转行已经不编程了。他本人和我一样也是在广州，所以私底下有和他聊过，作者吴哥他比较支持我继续维护这个项目，为了能不让这个开源项目荒废掉，所以我创建了一个Organization，期望有兴趣共同维护这个项目的伙伴可以加入进来。另外为了方便讨论交流，我建了一个QQ群：387051294 欢迎加入。

**Comment by xiaosong520** [comment]
目前正在重构优化代码中，大概过几天会发新版本出来，并更新说明文档。会新增一些设置选项来解决困扰大家已久的如字体大小/颜色/间距等

**Comment by AxingG** [comment]
谢谢大神们的努力

**Comment by xiaosong520** [comment]
作者已经把这个项目转交给我维护，已更新版本，添加了诸多方法供用户设置，会持续更新优化，欢迎大家参与维护优化，QQ群 387051294 。 遇到问题欢迎 提issue， pull request 优化。

**Comment by xiongwenzhi** [comment]
谢谢大神

**Comment by ALx8023** [comment]
大神  能像iOS那样不能选择今天之后的时间吗(只能选择今天之前的日期到当前日期)

**Comment by xiaosong520** [comment]
@ALx8023 目前还没能把所有情况完全考虑周全，之后会慢慢完善。急用的话可下载源码根据自己需求定制一下。

**Comment by ALx8023** [comment]
@xiaosong520 嗯嗯  好的  谢谢大神

**Comment by inshyma** [comment]
大神转什么行业了?请给我们指条迷路

**Comment by xiaosong520** [comment]
@inshyma 他和我说是搞文职类这一块了，应该是彻底转行了吧，大概就是这样

**Comment by s90304a123** [comment]
大神，是否有机会做到跟ios一样有弹簧效果呢? 先谢谢大神的努力了!

**Comment by BearEgg** [comment]
有'com.android.support:appcompat-v7:25.1.1'此版本的依赖

**Comment by xiaosong520** [comment]
@BearEgg 谢谢指出，已发现了这个问题所在，下个版本会除去掉Support依赖，并优化一些其他的小问题

**Comment by xiaosong520** [comment]
@s90304a123 目前还在优化其他的内容，这个效果等有时间了会考虑一下。

**Comment by stormlei** [comment]
持续关注...

**Comment by HoldMyOwn** [comment]
原作者从事哪个行业了,很好奇..

**Comment by xiaosong520** [comment]
@HoldMyOwn 上面评论有说

**Comment by xuminmin0405** [comment]
前两天导的3.0.4，测试运行没问题，今天打包报错冲突，看了许久发现更新了3.0.5，顿时哭晕。

**Comment by xiaosong520** [comment]
@xuminmin0405 更新一下就好，原有的方法无改动。

**Comment by is1988** [comment]
两横线之间的文字没有居中 感觉距离上面那条线更近一点 不知道是不是我设置间隔倍数的问题 请问有没有同感的

**Comment by xiaosong520** [comment]
@is1988 计算取值由于π是个近似值，稍微有点小偏差，还在调整中。

**Comment by breezehan** [comment]
顶一个!

**Comment by is1988** [comment]
@xiaosong520 哦原来是这样 我还天真的找了半天textview  结果没有找到 在什么地方改 - -#

**Comment by xuminmin0405** [comment]
@xiaosong520 昨日已更新，十分满足我的需求，赞一个

**Comment by SomnusWu** [comment]
@xiaosong520 有没有打算把原作者的其他开源项目 也继续维护 ~~~~

**Comment by xiaosong520** [comment]
@SomnusWu 比如？

**Comment by SomnusWu** [comment]
比如：https://github.com/saiwu-bigkoo/Android-ConvenientBanner

**Comment by xiaosong520** [comment]
@SomnusWu  这个库我没有使用过所以还没去研究它的源代码，暂时也还抽不出那么多时间维护很多个库，如果你有想法维护那个库的话，我可以和作者他本人说一下。

**Comment by PayneJay** [comment]
封装的很棒，但是具体的过程还是看的不是特别明白，自己得再研究一下吧

**Comment by aotian16** [comment]
辛苦了啊，开源需要持续的付出
