### ISSUE TITLE
选省市县的时候，名字太长会显示不全

### ISSUE THREAD

**Issue by a362310485** [Bigkoo/Android-PickerView#190]
选省市县的时候，名字太长会显示不全

**Comment by xiaosong520** [comment]
@a362310485 这个需要开发者自己在输入数据源的时候截取处理一下，因为在自定义控件里面截取的话，绘制会需要更多时间

**Comment by xiaosong520** [comment]
@a362310485 可以先尝试调整一下滚轮控件的文字大小，用setContentTextSize() 设置一下

**Comment by a362310485** [comment]
老版本直接升新版本有什么要注意的没

**Comment by totcw** [comment]
@a362310485  新版使用了创建者模式来构造,所以api有所改动

**Comment by xiaosong520** [comment]
@a362310485 可参照demo 中的Mainactivity 类，方法名有所改动，但使用起来比以前要简单一些。
