### ISSUE TITLE
该控件高度怎么控制

### ISSUE THREAD

**Issue by bigmanLau** [Bigkoo/Android-PickerView#191]
该控件高度怎么控制

**Comment by xiaosong520** [comment]
@bigmanLau 高度取的是滚轮的直径（滚轮圆的周长是由10个item的长度加起来得到的，所以高度和item的高度有关系）

**Comment by xiaosong520** [comment]
@bigmanLau item的高度可以通过设置 滚轮字体大小或者间距改变

**Comment by bigmanLau** [comment]
那我估计只能通过间距修改了 因为设计师要求字体大小固定，有间距这个api？

**Comment by bigmanLau** [comment]
找到了 setLine的那个方法，可以关闭issue了

**Comment by xiaosong520** [comment]
@bigmanLau 好的
