### ISSUE TITLE
如果一个界面有多个 picker，怎么取到正确的值？

### ISSUE THREAD

**Issue by liuzheng9110** [Bigkoo/Android-PickerView#192]

**Comment by xiaosong520** [comment]
@liuzheng9110 通过创建不同的picker对象来实现

**Comment by liuzheng9110** [comment]
@xiaosong520   能否在不重复创建对象的情况下提供相关方法获取呢？

**Comment by xiaosong520** [comment]
@liuzheng9110  能否详细描述一下你现在出现的问题？

**Comment by liuzheng9110** [comment]
@xiaosong520  界面有开始时间、结束时间，想用一个picker来显示，但取值是分开，目前回调只能对应一次点击，多次点击就得重新初始化设置 listener，是不是可以把 listener 拿出来单独设置或者能够提供统一方法获取多次点击的值？

**Comment by liuzheng9110** [comment]
@xiaosong520  3ks，已经找到方法解决了。

**Comment by xiaosong520** [comment]
@liuzheng9110 好的，问题解决就好
