### ISSUE TITLE
TimePickerView打开时，按返回键会交给当前Activity处理

### ISSUE THREAD

**Issue by yu-guorong** [Bigkoo/Android-PickerView#195]
TimePickerView处于开启状态时，能够消费掉`KEYCODE_BACK`事件是不是好点。

**Comment by xiaosong520** [comment]
@yu-guorong   这个是根据实现需求来设置的，可在Activity 中处理一下， demo 代码中有写，像这样：
` @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (keyCode == KeyEvent.KEYCODE_BACK) {
            if (pvTime.isShowing()) {
                pvTime.dismiss();
                return true;
            }
        }
   return super.onKeyDown(keyCode, event);`

**Comment by yu-guorong** [comment]
嗯   我在Activity中处理了     只是觉得如果加在控件本身  更方便一点
