### ISSUE TITLE
不可以修改contentext 颜色啊？

### ISSUE THREAD

**Issue by fuxianwen** [Bigkoo/Android-PickerView#197]

**Comment by fuxianwen** [comment]
可以添加一个 设置 contenttext 字体颜色修改 和  conten  item的高度吗

**Comment by xiaosong520** [comment]
有的：
`.setTextColorCenter()//设置选中内容字体颜色
.setTextColorOut() //设置未选中内容字体颜色
.setContentSize() //设置内容字体
.setLineSpacingMultiplier(1.6f)//设置间隔倍数`
