### ISSUE TITLE
支持英文吗？

### ISSUE THREAD

**Issue by fghjhuang** [Bigkoo/Android-PickerView#198]

**Comment by xiaosong520** [comment]
@fghjhuang 你好，支持的。确定，取消，标题，单位标签，内容文字，都可以自定义设置成英文的。

**Comment by fghjhuang** [comment]
是的，刚刚看到了，要升级到3.0.8版本，而且compile的名字也不同了，'com.contrarywind:Android-PickerView:3.0.8'，我一直在原来的基础上改成3.0.8，所以出错了
