### ISSUE TITLE
与其它项目有冲突，看了一下moudle里面也没用依赖什么东西

### ISSUE THREAD

**Issue by wZuriel** [Bigkoo/Android-PickerView#201]
Error:Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lcom/bigkoo/pickerview/BuildConfig;

**Comment by xiaosong520** [comment]
@wZuriel 看一下资源文件是否有重复的

**Comment by wZuriel** [comment]
@xiaosong520 我看了一下，没看到什么冲突的地方，我用2.X的版本没有提示冲突

**Comment by xiaosong520** [comment]
@wZuriel 错误日志有没有更多输出提示？

**Comment by wZuriel** [comment]
@xiaosong520 你是群主吗？我在群里发了消息了，是图片这个发不了

**Comment by xiaosong520** [comment]
@wZuriel 你好，请私窗弹一下我，之前下班了没注意群消息。
