### ISSUE TITLE
文字被压扁了点

### ISSUE THREAD

**Issue by wpq2014** [Bigkoo/Android-PickerView#202]
1、.setContentTextSize(20)//滚轮文字大小
      .setLineSpacingMultiplier(2.0f)//设置两横线之间的间隔倍数
      按上面设置跟iOS对比了下，能看出来文字被压扁了点，看了下源码计算高度的部分不是很懂。
2、**OptionsPickerView** 只有一级时，.setSelectOptions(selectedPosition) 设置了1但是还是选中第0项。

**Comment by xiaosong520** [comment]
@wpq2014 你好，是选中项文字被压扁了一点吗？另外 第二个问题我调试一下看是不是存在这个BUG

**Comment by wpq2014** [comment]
第二个问题是我错了，不好意思！ 我刚又测过了，刚才封装的时候重载调错了。。

**Comment by xiaosong520** [comment]
@wpq2014 好的，问题解决了就好

**Comment by wpq2014** [comment]
文字大小我设置了20，间隔2.0f，同样的文字跟iOS弹框对比确实扁了

**Comment by xiaosong520** [comment]
@wpq2014 这个只能说是做到精仿，计算取值难免有细微误差的。

**Comment by wpq2014** [comment]
恩，没事，这个库效果已经很屌了！ 非常感谢你们的分享和持续维护！！ GitHub怎么打赏了？
