### ISSUE TITLE
为什么联动的时候，不能二级、三级默认滚动到第一位

### ISSUE THREAD

**Issue by 0kai** [Bigkoo/Android-PickerView#206]

**Comment by xiaosong520** [comment]
@0kai 弹出的时候可以设置默认选中项，不过在滑动过程是没有处理还原到第一项的。

**Comment by 0kai** [comment]
@xiaosong520 希望能加一个这个的功能，还是有需求场景的

**Comment by xiaosong520** [comment]
@0kai  好的~目前是有对边界处理，防止数据越界。滑动的时候还原到第一项这个我后续会完善。
