### ISSUE TITLE
滚轮灵敏度无法调

### ISSUE THREAD

**Issue by kyymeade** [Bigkoo/Android-PickerView#211]
默认的滚轮滚动的太快了，滑动距离稍微大一些就十多个item过去了，希望可以有一个能够更改灵敏度的方法

**Comment by xiaosong520** [comment]
@kyymeade  你好，目前滑动速度是固定的。若需要改的话，引入Module 然后在WheelView 类里面找到这个变量：VELOCITYFLING，修改它的值就好了。

**Comment by kyymeade** [comment]
@xiaosong520 这个常量我看到了，谢谢

**Comment by xiaosong520** [comment]
@kyymeade 好的

**Comment by liuxuesong001** [comment]
我不想引入module 只想修改速度呢？VELOCITY_FLING
