### ISSUE TITLE
轮子对不齐

### ISSUE THREAD

**Issue by cjh1005221032** [Bigkoo/Android-PickerView#213]
轮子1            |    轮子2
今天(周一)    |    00:00-01:00
03-21(周二)  |    01:00-02:00

这样的数据，轮子2 的 单行行高 小于 轮子1 单行行高，导致右边轮子比左边轮子的高度小，然后就对不齐了。

**Comment by xiaosong520** [comment]
@cjh1005221032 新版本3.1.2 已修复问题，可以更新一下。
