### ISSUE TITLE
....

### ISSUE THREAD

**Issue by niantuo** [Bigkoo/Android-PickerView#214]
我选择的时间，，比如，，早上六点和下午六点，，出来的都是早上六点的时间，是需要设置什么 吗？

**Comment by xiaosong520** [comment]
@niantuo 这个是指timepicker分别弹出两次选择时间 还是给它设置起始终止时间？

**Comment by xiaosong520** [comment]
@niantuo 详细描述可以加QQ群或者私窗截图发一下给我，GitHub太方便表述

**Comment by niantuo** [comment]
非常抱歉啊，是我个人的问题，，String formatStr = "yyyy-MM-dd HH:mm:ss";我应该是把那个HH写成小写了，，结果是十二小时制的，问题就出来了，非常感谢

**Comment by xiaosong520** [comment]
@niantuo 不用客气，那我关闭issue了
