### ISSUE TITLE
多次SetPicker不同的数据，弹起时不会显示最新set的数据

### ISSUE THREAD

**Issue by tingbob** [Bigkoo/Android-PickerView#215]
目前不能支持setpicker不同数据会及时显示现有数据吗？
现在的结果是弹起时虽然显示的是第一次的数据，但是选择后返回的数据是后来最新set的数据。
如果要setpicker必须重新初始化才可以。
这个可以优化吗？

**Comment by xiaosong520** [comment]
@tingbob pvOptions.setSelectOptions() 调用这个方法设置一下就好了

**Comment by xiaosong520** [comment]
@tingbob  你的意思是设置选中项还是指数据源没更新？

**Comment by tingbob** [comment]
比如有两个数据源A{1,2},B{3,4}
一开始setpicker(A),弹起显示的是A的数据。
再setpicker(B),弹起提示还是显示A的数据，但是选择后回调过来的数据是B里面的数据。

**Comment by xiaosong520** [comment]
@tingbob 我刚刚调试了一下，数据是会有更新显示的

**Comment by tingbob** [comment]
setpicker我放了一维与二维数组setpicker(A,B)，会出现那个现象
sorry，只放一维的没这么设过，我以为都是如此。

**Comment by xiaosong520** [comment]
@tingbob 嗯，问题解决了吗？

**Comment by tingbob** [comment]
解决了。Thank you～
