### ISSUE TITLE
关于加入全国省市县

### ISSUE THREAD

**Issue by linxi926959** [Bigkoo/Android-PickerView#216]
看懂了你的demo。假如要加入全国的省市县，不可能一个一个new对象，然后一个一个地加到list中吧？有没有什么好的方法？

**Comment by xiaosong520** [comment]
@linxi926959 新的demo里有写了一个示例，解析json 的，在JsonDataActivity 类里面。

**Comment by linxi926959** [comment]
@xiaosong520 好的，我看看，谢谢。

**Comment by xiaosong520** [comment]
好的~
