### ISSUE TITLE
导入库编译出现下面的问题

### ISSUE THREAD

**Issue by ShawnWang520** [Bigkoo/Android-PickerView#218]
Error:Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Lcom/bigkoo/pickerview/BuildConfig;
Error:Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: Error while executing java process with main class com.android.dx.command.Main with arguments {--dex --num-threads=4 --output I:\SmartFanmi\app\build\intermediates\transforms\dex\debug\folders\1000\1f\main I:\SmartFanmi\app\build\intermediates\pre-dexed\debug\classes_2bbb7ba3c6e08100a8cdd647c7e4579b1182fea0.jar I:\SmartFanmi\app\build\intermediates\pre-dexed\debug\httpcore-4.2.4_fa74cb35ff0810aa7cb71ac0df14d67d6452ccdf.jar I:\SmartFanmi\app\build\intermediates\pre-dexed\debug\MPAndroidChart-v3.0.1_c8feb5a7c25a3e2fe5c207ee267be83a709018b7.jar I:\SmartFanmi\app\build\intermediates\pre-dexed\debug\classes_71fff533368ce38035e993d970ac40f85faa601c.jar I:\SmartFanmi\app\build\intermediates\pre-dexed\debug\fastjson-1.1.22_bf6892a78c7db70c76714e7e31e66b4e2a374c15.jar I:\SmartFanmi\app\build\intermediates\pre-dexed\debug\classes_dbc7bf77f357dfbcf19c9c85253ca2205cceb6d4.jar I:\SmartFanmi\app\build\intermediates\pre-dexed\debug\BaiduLBS_Android_61127749a049ef038de5c81b53798b89840651af.jar I:\SmartFanmi\app\build\intermediates\pre-dexed\debug\httpclient-4.2.5_651e48d90e10b6e2150ec58b49ab8604d576a7e1.jar I:\SmartFanmi\app\build\intermediates\pre-dexed\debug\systembartint-1.0.3_689518654cf7759fbb6027e9a62730c8bf40132a.jar I:\SmartFanmi\app\build\intermediates\pre-dexed\debug\ormlite-android-4.48_27ed81fb73011be0df1c9000664025b41048e8b2.jar I:\SmartFanmi\app\build\intermediates\pre-dexed\debug\ormlite-core-4.48_e9919a2582a02c37c76e4402b10a916e6b6020fb.jar I:\SmartFanmi\app\build\intermediates\pre-dexed\debug\support-annotations-24.1.1_f7ab9a15533c678b7cea6bc2f0253b886289e6f2.jar I:\SmartFanmi\app\build\intermediates\pre-dexed\debug\classes_0491baeb317b43790d9de070233ac5c1e4b0709f.jar I:\SmartFanmi\app\build\intermediates\pre-dexed\debug\classes_11c478d0cc39e50e9f4a24d2c4c1e12e5e58faa4.jar I:\SmartFanmi\app\build\intermediates\pre-dexed\debug\classes_40b667066881dcba76ee9cf49f823988342431cc.jar I:\SmartFanmi\app\build\intermediates\pre-dexed\debug\library-2.4.0_65d39d26d4f4068666de98a9e08ad288d1b67970.jar I:\SmartFanmi\app\build\intermediates\pre-dexed\debug\eventbus-2.4.0_8c08e6615d0ab42476257663371af41f03ce760b.jar I:\SmartFanmi\app\build\intermediates\pre-dexed\debug\classes_2494c56782aef2479912796707793199968aeef5.jar I:\SmartFanmi\app\build\intermediates\pre-dexed\debug\gson-2.3.1_a0d7f941c91bc1d9e8177b2e4201c45ddf782548.jar I:\SmartFanmi\app\build\intermediates\pre-dexed\debug\jpush-android-2.1.7_83aceb654a0364406534552b31e4f9c792b86bd6.jar I:\SmartFanmi\app\build\intermediates\pre-dexed\debug\org.eclipse.paho.client.mqttv3-1.0.2_f38fded9cfb80e697f24ed556b9dc3b8a6231847.jar I:\SmartFanmi\app\build\intermediates\pre-dexed\debug\universal-image-loader-1.9.4-SNAPSHOT_6a718f0f80d519c84db0bbd22df588b259b49164.jar I:\SmartFanmi\app\build\intermediates\pre-dexed\debug\classes_7e97d3455da16d38a769ba29b931bcee606b1c42.jar I:\SmartFanmi\app\build\intermediates\pre-dexed\debug\classes_73fefdbc73a37509c1e7d970f96d5e067aa4b802.jar I:\SmartFanmi\app\build\intermediates\pre-dexed\debug\classes_1580dd990c7ae4e66e8b1689b7cb78c7df68f8ca.jar I:\SmartFanmi\app\build\intermediates\pre-dexed\debug\debug_683fad23268d3f185f229c6edd4e8310a1270cd0.jar I:\SmartFanmi\app\build\intermediates\pre-dexed\debug\classes_5653ac437a14b4ba0a5507844085600fe3f18c9b.jar I:\SmartFanmi\app\build\intermediates\pre-dexed\debug\commons-codec-1.3_13cec56d8a29e2e6ec2b9967b18292f4b595efad.jar I:\SmartFanmi\app\build\intermediates\pre-dexed\debug\classes_66e5220d2a1bd8dbcf6f574a754e56623989e44e.jar I:\SmartFanmi\app\build\intermediates\pre-dexed\debug\ksoap2-android-assembly-2.6.5-jar-with-dependencies_724306157146b5ce9d454f40b6199e0be9b289b8.jar I:\SmartFanmi\app\build\intermediates\pre-dexed\debug\classes_dab817ad2eb2be14d714e6791b17f149bc394962.jar I:\SmartFanmi\app\build\intermediates\pre-dexed\debug\classes_5a814201b72e0ff4b21d0f5b0848a429477888bb.jar I:\SmartFanmi\app\build\intermediates\pre-dexed\debug\internal_impl-23.4.0_3cc24a93bf444c5f5d6a76067011f92085b5569b.jar I:\SmartFanmi\app\build\intermediates\pre-dexed\debug\classes_8face8950823c47f3e10c5588f1e3fba211a36c5.jar I:\SmartFanmi\app\build\intermediates\pre-dexed\debug\classes_923d8687daf3a7d854f4d403295ac94a0674b0b3.jar I:\SmartFanmi\app\build\intermediates\pre-dexed\debug\org.eclipse.paho.android.service-1.0.2_e0edccb145450c82ea1046250387dd12ca7e6d20.jar I:\SmartFanmi\app\build\intermediates\pre-dexed\debug\classes_36bc8a523cb0468365e05362e39b93d44da4092e.jar}
怎么解决？跪求

**Comment by xiaosong520** [comment]
@ShawnWang520 Clean 项目重建试一下
