### ISSUE TITLE
时间选择器只有两栏时，比如年月，右边的“月”字会顶到屏幕边缘，看上去不是很协调，能不能优化一下？

### ISSUE THREAD

**Issue by timshinlee** [Bigkoo/Android-PickerView#220]
如题，谢谢！

**Comment by xiaosong520** [comment]
@timshinlee 由于Wheelview 里面item的长度是不统一的，所以目前是把label文字居右绘制的。后续会考虑把时间选择器给优化一下排版。你也可以把源码改动一下，将内容和label文字的字符串拼接在一起然后再绘制。

**Comment by timshinlee** [comment]
@xiaosong520 秒回啊，好的，感谢！

**Comment by xiaosong520** [comment]
@timshinlee 已经上传了代码 新增了 isCenterLabel(false) 方法并设置 false ，则可以将label 添加到内容后面，就不会存在间隔太宽页面不美观的问题了
