### ISSUE TITLE
滑动至尽头

### ISSUE THREAD

**Issue by W2L** [Bigkoo/Android-PickerView#221]
手动慢慢滑动到尽头后，继续滑动会出现抖动的情况，并且有滚动方向与滑动方向不一致的情况。

**Comment by xiaosong520** [comment]
@W2L 这个是拖拽事件的问题，计算弧长取值稍微有点偏差，位置有偏移，所以需要手指松开后才能正确挪回。

**Comment by W2L** [comment]
@xiaosong520 在非loop的情况下，我发现，滑动到底部出现的抖动问题是由于WheelView中的onTouchEvent的630行的判断似乎有问题，如果将bottom和top的重新赋值的判断取消，就不会再出现这个问题了。

**Comment by xiaosong520** [comment]
@W2L 我检查一下，感谢反馈~

**Comment by xiaosong520** [comment]
@W2L 新版本已优化了这个问题，谢谢反馈问题。
