### ISSUE TITLE
时间选择器数据源的问题

### ISSUE THREAD

**Issue by tommyfeng** [Bigkoo/Android-PickerView#223]
能否自定义数据源？ 比如，我年份只需要 2016 和 2017，月份只需要 5、8、10，日份只需要 9、11、21这样子的格式，有可以设置数据的方法吗？

**Comment by tommyfeng** [comment]
这个感觉是不是条件选择器，只不过是换成了时间。。。。

**Comment by xiaosong520** [comment]
@tommyfeng 你可以稍微改动一下timepicker的源代码。 用条件选择器也可以，不过条件选择器需要注意大小月的日期和闰年。

**Comment by tommyfeng** [comment]
嗯，数据源是我自己控制的。我觉得用条件选择器应该比较适合。哈哈，多谢你的回复！

**Comment by xiaosong520** [comment]
@tommyfeng  ok ，那我就关闭issue了
