### ISSUE TITLE
ActionBar没有阴影效果

### ISSUE THREAD

**Issue by weinierfei** [Bigkoo/Android-PickerView#225]
activity里有ActionBar,效果如下;咋改?
![](http://7xrlse.com1.z0.glb.clouddn.com/0.png)

**Comment by xiaosong520** [comment]
@weinierfei 目测是由于ActionBar是显示在根部局上层导致的。因为现在picker的布局是拿的rootview作为父控件

**Comment by weinierfei** [comment]
是的  主题是有ActionBar的

**Comment by xiaosong520** [comment]
@weinierfei 把ActionBar 改成其他的控件写进布局应该就好了

**Comment by weinierfei** [comment]
这个我知道,一般ActionBar都是写在BaseActivity里的,不与界面布局一起的;所以才会问,有没有其他解决办法?

**Comment by xiaosong520** [comment]
@weinierfei 暂时只能这么处理，因为ActionBar 也是添加在根布局上方，picker 没办法遮盖住它。

**Comment by weinierfei** [comment]
![](http://7xrlse.com1.z0.glb.clouddn.com/000.png)
直接将view添加到decorView,不获取android.R.id.content可以避免这个问题,不知道这样做行不行?

**Comment by mhlistener** [comment]
我是这么处理的，修改BasePickerView，使用dialog就可以解决阴影问题
![image](https://cloud.githubusercontent.com/assets/18526628/25832210/cfe533e0-349b-11e7-9647-d54c15a4251c.png)
![image](https://cloud.githubusercontent.com/assets/18526628/25832227/f32a0d3a-349b-11e7-87a5-ad22f9bae605.png)
