### ISSUE TITLE
item start position

### ISSUE THREAD

**Issue by kainjinez** [Bigkoo/Android-PickerView#226]
OptionsPickerView keeps last scroll, even they scroll but hide it instead of select, position for next showing. How to prevent it? I want OPV always start at picked position. How to do that? I find in the source code but  didnt found anything.

**Comment by xiaosong520** [comment]
@kainjinez   Hi~ do you mean that you need to set the selected item?  please add the following code： pvOptions.setSelectOptions(0,1,2)

**Comment by kainjinez** [comment]
Hi. Let me clear this.
I have 10 items in list. I scroll to position 4 then click OK.
After that, I open wheel again, **It started at position 4** i scroll to postion 6. But cancel.
Next time I open the wheel, **It started at position 6**.
All I want to do is: every next time i open the wheel, it will start at last selected position.

**Comment by xiaosong520** [comment]
@kainjinez  That is all right, you need save the selected positions after click OK( in onOptionsSelect method ), and then ,before you open OptionsPickerView , add the following code : pvOptions.setSelectOptions(options1, option2, options3) .

**Comment by kainjinez** [comment]
I'll check it and reply soon. Thanks alot anyway.

**Comment by xiaosong520** [comment]
@kyuyi You are welcome

**Comment by kainjinez** [comment]
It doesn't work for me. I have to edit a bit code to override `setOnDismissListener`.  Then i setSeectOptions. After that, i have to setPicker again. Then now it works. Thanks.
