### ISSUE TITLE
三级联动-如何动态获取数据

### ISSUE THREAD

**Issue by ganshenml** [Bigkoo/Android-PickerView#227]
查看了demo，发现几级联动都是在已有确定的数据源的情况下进行的。
一般省市县三级联动，先选定了省这一级别，然后接口去调用该省下的市的数据。
从demo中没有看出有可供去在动态获取的方法？

**Comment by xiaosong520** [comment]
@ganshenml 如果是这种方式去请求接口数据的话，切换选项过程会造成网络请求太频繁，而且弱网环境延迟太高，切换会很慢，体验不好。

**Comment by xiaosong520** [comment]
@ganshenml 若后台接口返回格式不能变，建议你更换成京东地区选择的那种方案。若使用该方案的话，建议第一次加载的时候拿好数据保存在本地，或者直接放在项目assets目录下使用，避免网络因素影响体验效果。

**Comment by ganshenml** [comment]
@xiaosong520 嗯。这样看来的话，这种控件不太适用于动态获取数据的情况了。

**Comment by XinYiWorld** [comment]
我按照demo里做的，怎么所有的省关联的市只有北京市，而且如果开启联动就直接崩溃了。

**Comment by tinynong** [comment]
分成两个。。。
