### ISSUE TITLE
如何设置不选中今天之前的日期

### ISSUE THREAD

**Issue by hamuamu0** [Bigkoo/Android-PickerView#233]
如何设置不选中今天之前的日期

**Comment by xiaosong520** [comment]
请参考issue230: https://github.com/Bigkoo/Android-PickerView/issues/230

**Comment by xiaosong520** [comment]
@hamuamu0 demo 中 initTimePicker()方法里的示例。

**Comment by xiaosong520** [comment]
第一步：Calendar startDate = Calendar.getInstance(); 获取当前时间。
然后：  setRangDate(startDate,endDate)，就可以了

**Comment by stevenchans** [comment]
目前没有支持到 小时分钟 秒数
