### ISSUE TITLE
回调返回值能否根据设置的时间类型自动调整 

### ISSUE THREAD

**Issue by liuzheng9110** [Bigkoo/Android-PickerView#236]
比如设置的是年月日，回调的结果也是年月日， 不用显示时分秒 00：00：00

Date date = WheelTime.dateFormat.parse(wheelTime.getTime());

**Comment by xiaosong520** [comment]
@liuzheng9110 好好理解一下Format相关知识点。

**Comment by xiaosong520** [comment]
@liuzheng9110 可自行格式化取所需要的值。
