### ISSUE TITLE
可以在optionItem上增加监听吗

### ISSUE THREAD

**Issue by candrwow** [Bigkoo/Android-PickerView#237]
比如日期上，当停留在2017 04 01上时，点击04 可以打开键盘输入12，确定后变成2017 12 01.

**Comment by xiaosong520** [comment]
@candrwow 暂时还不支持，需要自己改动源码添加逻辑进行处理

**Comment by candrwow** [comment]
我在setLayoutRes（R.layout.pickerview_options中调用WheelView wheelView = (WheelView) findViewById(R.id.options1);然后为什么wheelView会是null啊

**Comment by xiaosong520** [comment]
@candrwow 需要指定容器再获取资源id，请仔细对比demo的写法。

**Comment by candrwow** [comment]
好的，谢谢

**Comment by candrwow** [comment]
遇到个新问题，如果在LayoutRes里加入一个edittext，唤醒键盘时，键盘会完全遮挡pickerview，我的当前activity的android:windowSoftInputMode="adjustResize"。
