### ISSUE TITLE
关于时间选择器

### ISSUE THREAD

**Issue by XinYiWorld** [Bigkoo/Android-PickerView#240]
请问时间选择器怎么在条目的最上方加一个“至今”?

**Comment by xiaosong520** [comment]
这个是指在布局中添加一个固定的文字？ 若是的话，可以考虑自定义布局。如果是指在Item上面添加的话，则需要自行改动一下源码做定制。

**Comment by XinYiWorld** [comment]
我指的在第1列“年”的最上面加一个至今选项，不是自定义布局。

**Comment by XinYiWorld** [comment]
很多招聘的app，都在工作经历，从1991年 -至今。这个年应该是可以扩展的。

**Comment by mcgrady911** [comment]
日期选项会出现越界的情况，然后自动转跳上个月，有遇到过的+1

**Comment by xiaosong520** [comment]
@mcgrady911 月份是0-11，注意demo的注释说明。
