### ISSUE TITLE
您好，请教一个关于开源库的问题

### ISSUE THREAD

**Issue by XinYiWorld** [Bigkoo/Android-PickerView#241]
1.我生成一个compile链接，为什么我在搜索某一个类名的时候，只能搜到.class文件
而你们的开源库.class文件和.java文件都能看到。

2.在我重写一个类的方法时，方法名和我源码里的方法名不一样。
   这是我重写时的变量名都是i,t什么的。
   @Override
    public <T> void onSuccess(int i, BaseHttpResponseBean baseHttpResponseBean, T t) {

    }
 
   这是我源码里的方法
   <T> void onSuccess(int requestCode, BaseHttpResponseBean codeInfoBean,T successBean);

所以我想请教一下，在生成compile的链接时候，是不是要配置什么才能把源码打包进去？

**Comment by weinierfei** [comment]
```
    task sourcesJar(type: Jar) {
        from android.sourceSets.main.java.srcDirs
        classifier = 'sources'
    }
    task javadocJar(type: Jar) {
        from android.sourceSets.main.java.srcDirs
        classifier = 'javadoc'
    }

    // 产生相关配置文件的任务
    artifacts {
        archives javadocJar
        archives sourcesJar
    }
```

**Comment by XinYiWorld** [comment]
您这使用的是JFrog Bintray吧，我用的是JitPack。

**Comment by XinYiWorld** [comment]
非常感谢大神的帮助！
