### ISSUE TITLE
修改动画速度

### ISSUE THREAD

**Issue by xuwab** [Bigkoo/Android-PickerView#243]
你好，上次你合了我的Dialog动画分支，但是后面你改了。我最新版本接入公司项目，发现Dialog弹出动画太慢了，会让用户误以为是性能问题。下个版本能不能把时长改为这个，android:duration="@android:integer/config_shortAnimTime"

**Comment by xiaosong520** [comment]
@xuwab  现在dialog样式下是400毫秒时长，我下个版本改成和默认样式一样的时长吧，300毫秒。
