### ISSUE TITLE
运行报错： Caused by: java.lang.ClassNotFoundException: Didn't find class "iqlib.bigkoo.pickerview.lib.WheelView" on path: DexPathList

### ISSUE THREAD

**Issue by chenguo4930** [Bigkoo/Android-PickerView#244]
android.view.InflateException: Binary XML file line #19: Error inflating class iqlib.bigkoo.pickerview.lib.WheelView

.build的时候，就报这个错了，我再gradle中添加了依赖，请问为什么啊

**Comment by xiaosong520** [comment]
@chenguo4930 请检查布局代码第19行。

**Comment by chenguo4930** [comment]
@xiaosong520 我找到原因了，我的项目中的自定义view中有一个WheelView，我改了下就行了
