### ISSUE TITLE
这个控件太复杂了 ,能不能接口化?

### ISSUE THREAD

**Issue by xinle** [Bigkoo/Android-PickerView#260]
比如说我本来只需要使用城市选择的功能,但是里面有很多和城市选择无关的代码.一般的项目如果不是很频繁使用类似的选择功能的话很难整个将你这个工程导入,我的意思是能不能先做一个很底层的一个只有UI的控件没有任何其他的逻辑, 其他的功能比如城市选择等,你可以再次实现,这样你可以不用整天因为别人一个需求就再加一遍,可能意味着你要写很多的module(或者有其他方法),但是这样的话底层的那个控件就可以应用非常广泛 ,(举个不恰当的例子,google的v4包可以分功能进行导入)

**Comment by xiaosong520** [comment]
最近工作比较忙，等时间充足的时候会考虑在下个大版本做一些优化，一般如果想简化代码定制化的话，可以引入代码自行删减和修改不需要用到的部分。
