### ISSUE TITLE
使用该组件怎样计算时间差

### ISSUE THREAD

**Issue by iamZ2z** [Bigkoo/Android-PickerView#264]
请问onTimeSelect方法获取的date怎么用于计算时间差呢，无法直接date.getTime()进行相减获得

**Comment by xiaosong520** [comment]
@iamZ2z 可以 format 格式化之后进行计算，这个需要开发者自己进行逻辑处理。

**Comment by AlvinQiang** [comment]
public static int getGapCount(Date startDate, Date endDate) {
        Calendar fromCalendar = Calendar.getInstance();
        fromCalendar.setTime(startDate);
        fromCalendar.set(Calendar.HOUR_OF_DAY, 0);
        fromCalendar.set(Calendar.MINUTE, 0);
        fromCalendar.set(Calendar.SECOND, 0);
        fromCalendar.set(Calendar.MILLISECOND, 0);

        Calendar toCalendar = Calendar.getInstance();
        toCalendar.setTime(endDate);
        toCalendar.set(Calendar.HOUR_OF_DAY, 0);
        toCalendar.set(Calendar.MINUTE, 0);
        toCalendar.set(Calendar.SECOND, 0);
        toCalendar.set(Calendar.MILLISECOND, 0);

        return (int) ((toCalendar.getTime().getTime() - fromCalendar.getTime().getTime()) / (1000 * 60 * 60 * 24));
    }


用这个方法可以直接计算出时间差
