### ISSUE TITLE
关于限定时间内选择时间的问题

### ISSUE THREAD

**Issue by mhlistener** [Bigkoo/Android-PickerView#268]
比如说设定滚轮 2017-04-01 到 2017-05-01.比如选择了4.15号，这个时候快速滑月份滚动条到5月份，然后点击确定。回调的结果显示  2017-05-15.已经超出时间范围了。

**Comment by xiaosong520** [comment]
@mhlistener 这个是切换选项的时候，适配器还没完成更新数据的步骤就点击了确定导致日期数据不对。可以做一下适当的提示逻辑。
