### ISSUE TITLE
二级联动失败

### ISSUE THREAD

**Issue by wd910617** [Bigkoo/Android-PickerView#271]
第一级条目存在数据
第二级数据不存在数据，且该条数据是第一个，这时候第一级不论如何滚动第二级不出现
数据：
第一级：
List  datas = new ArrayList<>();
datas.add(obj1);
datas.add(obj2);

第二级：
List<List<>> data2s = new ArrayList<>();
List<> data2_1s = new ArrayList<>();
data2s.add(data2_1s );
List<> data2_2s = new ArrayList<>();
data2_2s.add(obj1);
data2s.add(data2_2s );

这样的数据会出现无论如何变化二级不在显示。

**Comment by xiaosong520** [comment]
@wd910617 需要对数据进行非空判断，如果是空，则设置一个“”空字符串进去。
