### ISSUE TITLE
我想设置时间选择器中的某几项颜色跟其他项的颜色不一样, 请问可以吗?

### ISSUE THREAD

**Issue by wahyip** [Bigkoo/Android-PickerView#274]
有个需求, 就是一开始我就知道了哪些时间段不可选, 然后在填充picker的时候, 我想设置这些时间段的选项颜色跟其他选项颜色不一样, 请问这个控件可以做到吗?

**Comment by xiaosong520** [comment]
@wahyip 目前来说没有做这个功能，你可以自己改动一下Wheelview 类的源代码来实现这个功能。
