### ISSUE TITLE
库引入错误

### ISSUE THREAD

**Issue by heaton0308** [Bigkoo/Android-PickerView#278]
报错提示：Error:(54, 13) Failed to resolve: com.contrarywind:Android-PickerView:3.2.5
<a href="openFile:/Users/heaton/work/android/workspace/ecloud_app/app/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Comment by xiaosong520** [comment]
@heaton0308 检查一下命名或者字符串是否有误，或者网络问题。

**Comment by yangfar** [comment]
请问解决了吗
