### ISSUE TITLE
请教一下build.gradle 里面dependencies 的是什么？可以

### ISSUE THREAD

**Issue by pdog18** [Bigkoo/Android-PickerView#280]
dependencies {
       ....

        classpath 'com.github.dcendents:android-maven-gradle-plugin:1.4.1'

        classpath 'com.novoda:bintray-release:0.4.0'
    }

请问一下这两个依赖是什么？
因为需要对字体大小进行修改所以，想通过导入module的方式，但是发现需要添加这两项才可以编译通过，请问下这两个是什么什么？

**Comment by xiaosong520** [comment]
@pdog18 这个是上传代码到Jcenter 的插件，可以删除。工程目录下面gradle 配置也需要一起删掉才行。

**Comment by xiaosong520** [comment]
@pdog18 文字大小可以设置setContentTextSize 来进行修改

**Comment by pdog18** [comment]
@xiaosong520 以前版本是修改不了，现在提供了。。我改完了以后才发现，于是就很尴尬
这两个依赖都是用作上传代码的？学习了，谢谢你

**Comment by xiaosong520** [comment]
@pdog18 是的，你也可以google 百度查一下上传到Jcenter的技术博客。

**Comment by pdog18** [comment]
@xiaosong520 
我将这两行注释掉了以后发现编译不通过，我又可耻的打开注释了= =，以后再学习下，谢谢
