### ISSUE TITLE
Introducing min font size Builder setter?

### ISSUE THREAD

**Issue by mitsest** [Bigkoo/Android-PickerView#283]
Hi, thanks for your plugin.
I 'm trying to use it in a project, in order to display addresses inside it. Thing is, when strings get too big, the font size makes the text almost impossible to read.

I was wondering if  it's in your plans to introduce a minFontSize call (prefferrably at the Builder - setMinFontSize(15) -), and, during your text transformations, if you notice that you have to go even smaller, add ellipsis characters instead.

Care to comment?

Thanks again!
Dimitris

**Comment by xiaosong520** [comment]
@mitsest Hello, You can determine the length of the item when you set it，if it is too big, cut the part  what you want to display. As follows:  

if( item.length>maxlength ){
 item = item.substring( 0, maxlength )+"...";
}

**Comment by mitsest** [comment]
Hi @xiaosong520 and thanks for the fast reply.

Are you implying I should fork your repo, or should I put this block of code, inside an override, during Builder initialization?

Thanks :)

**Comment by xiaosong520** [comment]
@mitsest No, you don't have to ， Just need do above  before setPicker:

 for (int i = 0; i < cardList.size(); i++) {
            if (cardList.get(i).getCardNo().length() > 6) {
                String str_item = cardList.get(i).getCardNo().substring(0, 6) + "...";
                cardList.get(i).setCardNo(str_item);
            }
        }
 pvOptions.setPicker(cardList);


------------------------------------If the entity class implements the interface, Which is also OK:
public class CardBean implements IPickerViewData {
    String cardNo;

    public String getCardNo() {
     if (cardNo.length() > 6) {
            cardNo = cardNo.substring(0, 6) + "...";
        }
        return cardNo;
    }

    public void setCardNo(String cardNo) {
        this.cardNo = cardNo;
    }

**Comment by mitsest** [comment]
Ah, I see.
But what about different screen sizes? We might have to "cut" more letters depending on screen width. That's why I suggested using fontSize and adding a check (maybe inside reMeasureTextSize in WheelView.java) ??

Thanks

**Comment by xiaosong520** [comment]
@mitsest yes
