### ISSUE TITLE
时间选择中的回调接口中，参数View为什么都是空的？

### ISSUE THREAD

**Issue by T-mans** [Bigkoo/Android-PickerView#285]
这个view指的谁呢？我原来是想通过view获得id，给不同的控件进行设置。 
但是v总是把空指针异常？
mTimePickerView = new TimePickerView.Builder(this, new TimePickerView.OnTimeSelectListener() {
            @Override
            public void onTimeSelect(Date date, View v) {//选中事件回调
                long time = date.getTime();
                switch (v.getId())  {
}

**Comment by xiaosong520** [comment]
@T-mans 调用show()方法的时候需要传递view控件进来，用于判断是点击哪个控件弹出的。
