### ISSUE TITLE
 java.lang.NoSuchFieldError: com.bigkoo.pickerview.R$id.rv_topbar

### ISSUE THREAD

**Issue by sili6996** [Bigkoo/Android-PickerView#292]
一直找不到这个ID是怎么回事

**Comment by xiaosong520** [comment]
@sili6996 这个Id所在布局文件重复冲突了，找到本地重复的xml文件更改一下命名即可。

**Comment by sili6996** [comment]
👌

**Comment by wangsixsix66** [comment]
并未解决～

**Comment by shaozucheng** [comment]
这个问题的原因是，下面这个几个xml文件重名了
![image](https://user-images.githubusercontent.com/18187185/48131258-6de81e80-e2ca-11e8-90e6-719669b17b2d.png)
找到这个几个xml文件，把文件的名字重新命名就可以解决了
