### ISSUE TITLE
对话框只能是滚轮的,能不能添加一个属性,设置不是滚轮的,平铺的那种?

### ISSUE THREAD

**Issue by jinweihua123** [Bigkoo/Android-PickerView#297]

**Comment by cokuscz** [comment]
同求这个问题，怎么设置这个滚轮的弧度？

**Comment by xiaosong520** [comment]
@jinweihua123 暂时还不支持，因为item总条目不同，偏差距离也不同。改动了总条目之后会有item显示偏移不在正中间的问题。有需要的话可以改改WheelView类把条目总数改成自己需要的，然后修正一下该条目数量下的偏移差。

**Comment by winxinxinxin** [comment]
条件选择器的样式都是平铺的，时间选择器不能设置平铺的？
