### ISSUE TITLE
TimePickerView 设置选择出生日期时，能不能距当前近的设置为startTime，远的设置为endTime

### ISSUE THREAD

**Issue by foxsent** [Bigkoo/Android-PickerView#299]
确切将是将当前时间设置为startTime，过去的时间设置为endTime，意思也就是时间倒序输出可以吗？我看你源码加了限制，不知道下个版本能添加此功能吗

**Comment by xiaosong520** [comment]
@foxsent 不好意思，最近工作较忙，没有及时回复。这个功能需求还是比较小众的，你可以自行改改源代码来实现功能。
