### ISSUE TITLE
setType  必须设置 6 个

### ISSUE THREAD

**Issue by liuzheng9110** [Bigkoo/Android-PickerView#307]
setType  type.length 必须设置 6 个，否则会抛出异常  type[] length is not 6

是否可以将数组换成 可变参数

**Comment by xiaosong520** [comment]
@liuzheng9110 因为之前用枚举的方式会导致排列组合问题需要生成很多代码，组合需求也不好控制，所以后面就改成用布尔数组分别控制年月日时分秒的显示与否了。
