### ISSUE TITLE
Make picker becomes widget

### ISSUE THREAD

**Issue by kainjinez** [Bigkoo/Android-PickerView#308]
How to make this possible?
I want to implement this into a view, not a dialog picker. Thanks

**Comment by xiaosong520** [comment]
@kainjinez  step1: setDecorView(parentView)  before build().
                  step2: custom layout , and then delete title bar .
                  step3: pvTime.setKeyBackCancelable(false);

You can refer to here [TestFragment.java](https://github.com/Bigkoo/Android-PickerView/blob/master/app/src/main/java/com/bigkoo/pickerviewdemo/TestFragment.java
)
