### ISSUE TITLE
如何去掉或隐藏''取消'，"确定"按钮？

### ISSUE THREAD

**Issue by aloe20** [Bigkoo/Android-PickerView#309]
当我调用setDecorView在View中显示时，不希望有"取消"，"确定"按钮，该如何去掉呢(将标题栏去掉)？

**Comment by xiaosong520** [comment]
@aloe20 用自定义布局可以去掉，通过setLayoutRes方法来传入自定义布局xml，具体请参考demo [MainActivity.java](https://github.com/Bigkoo/Android-PickerView/blob/master/app/src/main/java/com/bigkoo/pickerviewdemo/MainActivity.java)
