### ISSUE TITLE
省市联动，options1Items里面我放的是对象，但是显示出来的是对象的全路径名字

### ISSUE THREAD

**Issue by xiaoDongBei90** [Bigkoo/Android-PickerView#310]
省市联动，options1Items里面我放的是对象，但是显示出来的是对象的全路径名字，我对象里面没有name字段，你那面是不是取的name字段，放置在wheelview上的呀？

**Comment by xiaosong520** [comment]
@xiaoDongBei90 实体类需要 implements IPickerViewData ，方法里面return 填你需要显示的内容，字符串类型的。

**Comment by xiaosong520** [comment]
@xiaoDongBei90 不一定是name字段，你需要显示什么字段就填什么。

**Comment by xiaoDongBei90** [comment]
跪谢！已星⭐

发自网易邮箱大师


在2017年06月28日 18:22，xiaosongzeem 写道：

@xiaoDongBei90 不一定是name字段，你需要显示什么字段就填什么。

**Comment by MankinChung** [comment]
重写对象的方法，就可以正常显示了

`@Override
    public String toString() {
        return “填你需要显示的内容”;
    }`

**Comment by xiaosong520** [comment]
@MankinChung 没什么问题，不过一般情况下建议用我之前说的那种办法好点。
