### ISSUE TITLE
I get a bug in version 3.2.5,I need help

### ISSUE THREAD

**Issue by zhhao226** [Bigkoo/Android-PickerView#311]
java.lang.NoSuchFieldError: No static field rv_topbar of type I in class Lcom/bigkoo/pickerview/R$id; or its superclasses (declaration of 'com.bigkoo.pickerview.R$id' appears in /data/app/cn.com.ecarx.ericsson.gnetlink-1/base.apk:classes32.dex)

**Comment by xiaosong520** [comment]
@zhhao226  The layout xml file which contains "rv_topbar" is in conflict, please check your project and make sure that  it not duplicated.  you can see  #292
