### ISSUE TITLE
三级联动的时候，如果有一栏是空数据会角标越界

### ISSUE THREAD

**Issue by Ayanokouji-Kenn** [Bigkoo/Android-PickerView#317]
似乎是因为“判断如果旧位置没有超过数据范围，则沿用旧位置，否则选中最后一项”
旧位置随便是几，当移动到空数据列表的时候，肯定就超出数据范围，于是给他选择最后一项就是list.size()-1,此时会选中-1，就越界了。

**Comment by xiaosong520** [comment]
@Ayanokouji-Kenn item的值不能为null ，需要进行非空判断，如果为空则设置“”字符串。

**Comment by Ayanokouji-Kenn** [comment]
集合就是空的，没有item。
目前解决办法是 是空集合，也给他`emptyList.add("")`。来避免上述问题找到-1角标。

**Comment by xiaosong520** [comment]
@Ayanokouji-Kenn 是的~否则get就会报空指针异常。
