### ISSUE TITLE
有问题啊

### ISSUE THREAD

**Issue by tianqiujie** [Bigkoo/Android-PickerView#318]
![image](https://user-images.githubusercontent.com/2835129/27938952-29457f18-62f4-11e7-9177-d62fa5f3d8ff.png)

**Comment by xiaosong520** [comment]
@tianqiujie可以用 isCenterLabel 方法，参数填false ； 或者用自定义布局，把默认label设置为”“，然后自己在自定义布局里面添加六个Textview写上“年”月“日”时“分”秒“。

**Comment by xiaosong520** [comment]
或者把年份的那个wheelview  layout_weight 改成1.1
