### ISSUE TITLE
用自定义布局，修改分割线颜色不起作用，希望大神修改一下！！！

### ISSUE THREAD

**Issue by 897902334** [Bigkoo/Android-PickerView#319]
我按照demo的自定义布局做了，修改分割线颜色不起作用，设置透明也没用！！！

**Comment by 897902334** [comment]
版本： V3.2.5

**Comment by xiaosong520** [comment]
@897902334 setDividerColor(Color.DKGRAY) 方法是没有任何问题的。检查自己的代码是否有误，不能直接R.color.xxx 来设置，具体原因请自行查资料。
