### ISSUE TITLE
选择生日出现个别日期选择和显示不一致的问题

### ISSUE THREAD

**Issue by che5277** [Bigkoo/Android-PickerView#321]
选择生日出现个别日期无法回显情况。 1986年：5月5日-9月14日 1987年：4月13日-9月12日 1988年：4月11日-9月10日 1989年：4月17日-9月16日 1990年：4月16日-9月15日 1991年：4月15日-9月14日 选择以上阶段内的生日时，点击确定后，回显的日期为前一日。 如：选择1986年5月5日，点击确定后，回显的为1986年5月4日。导致如果想回显1986年5月4日可以选择1986年5月4或5日，而1986年9月14日永远无法回显（因为问题日期是1986年5月5日-9月14日）

模拟器没有该问题，使用真机就会出现这个问题（使用的是华为EMUI5.0和EMUI5.1，介于Android5.0~7.0）

**Comment by xiaosong520** [comment]
@che5277 系统Calendar的月份是0-11, 所以如果调用了Calendar的set方法来设置时间, 则月份的范围也要设置成0-11。刚刚也用小米以及华为EMUI4.0系统的手机上调试了，设置了你上面所说的时间段，没有复现出问题场景。若你代码是按照正常的写法来写的，但只是华为个别机型出问题，则可能是由于这些定制过的系统改动了Calendar的逻辑导致的。

**Comment by xiaosong520** [comment]
@che5277
Android系统原生 Calendar 的set方法源码如下，注释部分google工程师已经有说明：
 `/**
     * Sets the values for the calendar fields <code>YEAR</code>,
     * <code>MONTH</code>, and <code>DAY_OF_MONTH</code>.
     * Previous values of other calendar fields are retained.  If this is not desired,
     * call {@link #clear()} first.
     *
     * @param year the value used to set the <code>YEAR</code> calendar field.
     * @param month the value used to set the <code>MONTH</code> calendar field.
     * Month value is 0-based. e.g., 0 for January.
     * @param date the value used to set the <code>DAY_OF_MONTH</code> calendar field.
     * @see #set(int,int)
     * @see #set(int,int,int,int,int)
     * @see #set(int,int,int,int,int,int)
     */
    public final void set(int year, int month, int date)
    {
        set(YEAR, year);
        set(MONTH, month);
        set(DATE, date);
    }`
