### ISSUE TITLE
二级联动时第一级重复出现

### ISSUE THREAD

**Issue by MXYJiang** [Bigkoo/Android-PickerView#322]
options1Items.add(new ProvinceBean(0, "山东"));

 ArrayList<String> options2Items_01 = new ArrayList<>();
        options2Items_01.add("青岛");
        options2Items_01.add("烟台");
        options2Items_01.add("潍坊");
        options2Items_01.add("威海");
        options2Items_01.add("日照");
        options2Items_01.add("东营");
        options2Items_01.add("滨州");

点击出现选择弹窗的时候，出现一次，“山东”就多一条，弹出一次，一条山东，再弹一次，两条山东。。。。

**Comment by xiaosong520** [comment]
@MXYJiang 请检查自己代码写法是否有误。
