### ISSUE TITLE
Problem with datas

### ISSUE THREAD

**Issue by helsephas** [Bigkoo/Android-PickerView#323]
Hello, first, i m sorry i don't speak chinese.
I want to know if i can adapt the list at runtime for exemple:
- wheel A contains A1,A2,A3
- wheel B contains B1A1,B2A1,
                                B1A2,B2A2,
                                B1A3,B2A3,
So if A1 if selected B1A1 and B2A1 is showing, A2 B1A2 and B2A2, etc , ...   
Thanks a lot
--------------------------------------------

我试图用中文来传播
你好，首先，我很抱歉，我不会说中文。
我想知道我是否可以在运行时调整列表，例如：
轮A包含A1，A2，A3
轮B包含B1A1，B2A1，
                                B1A2，B2A2，
                                B1A3，B2A3，
所以如果A1如果选择B1A1和B2A1显示，A2 B1A2和B2A2等...

**Comment by xiaosong520** [comment]
@helsephas  You mean that you need the options change as long as item changes? or next time you open it, change the default selection?  “So if A1 if selected B1A1 and B2A1 is showing, A2 B1A2 and B2A2, etc , ...”  Can you describe it more clearly? I don't quite understand this. Waiting for your reply~

**Comment by helsephas** [comment]
Yes the options2 changes as long as item changes in option 1. Its seems to be like this : https://github.com/Bigkoo/Android-PickerView/blob/master/preview/JsonData.gif.

**Comment by xiaosong520** [comment]
@helsephas The steps to add datas are as follows:

```
private ArrayList<Entity> options1Items = new ArrayList<>();
private ArrayList<ArrayList<Entity>> options2Items = new ArrayList<>();

        //options1 data
        options1Items.add(A1);
        options1Items.add(A2);

        //options2
        ArrayList<String> options2Items_02 = new ArrayList<>();
        options2Items_02.add(B11);
        options2Items_02.add(B12);
        ArrayList<String> options2Items_01 = new ArrayList<>();
        options2Items_01.add(B21);
        options2Items_01.add(B22);
        options2Items.add(options2Items_01);
        options2Items.add(options2Items_02);
```

**Comment by xiaosong520** [comment]
@helsephas It can be either data of type String or entity data. If you add entity data，your entity class need implements ”IPickerViewData“ interface, and then, In the "getPickerViewText" method, returns the String data what you needs to be displayed.

**Comment by xiaosong520** [comment]
@helsephas  set linkage picker data after you add data list, like this:
```
pvOptions.setPicker(options1Items, options2Items);
//or
pvOptions.setPicker(options1Items, options2Items,options3Items);
```

**Comment by helsephas** [comment]
Thanks for your replies.
I have make so try but i m still blocked with this code and i seem to use exactly like you

I used this like this : 
             var pickerViewDates =  MyOptionsPickerView<String>(this)
            pickerViewDates.setTitle(this.resources.getString(R.string.shopping_cart_pick_date_title))
            var now : Date = Date()
            var days : ArrayList<String> = ArrayList()
            var hours : ArrayList<ArrayList<String>> = ArrayList()
            var minutes : ArrayList<ArrayList<String>> = ArrayList()
           //init arrays
            pickerViewDates.setPicker(days,hours,minutes,true)
            pickerViewDates.setCyclic(true,true,true)
            pickerViewDates.show()

-> I get an error because type is mismatching (required: ArrayList<String!>! found ArrayList<ArrayList<String>>

**Comment by xiaosong520** [comment]
@helsephas  Do you need to use timePicker?  you can do that:
```
        Calendar selectedDate = Calendar.getInstance();
        Calendar startDate = Calendar.getInstance();
        startDate.set(2013, 0, 1);

        Calendar endDate = Calendar.getInstance();
        endDate.set(2017, 11, 1);

        pvTime = new TimePickerView.Builder(this, new TimePickerView.OnTimeSelectListener() {
            @Override
            public void onTimeSelect(Date date, View v) {//callback
            }
        })
                .setType(new boolean[]{true, true, true, false, false, false})
                .setLabel("", "", "", "", "", "")
                .setDividerColor(Color.DKGRAY)
                .setContentSize(21)
                .setDate(selectedDate)
                .setRangDate(startDate, endDate)
                .build();
    }
```

**Comment by xiaosong520** [comment]
@helsephas  Calendar's month value is 0-based. e.g., 0 for January.

**Comment by helsephas** [comment]
I can't use time picker because i got a set of ranges dates for example i will get 
17 july  8->16 hours 0-> 59 minutes
19 july  8->16 hours 0-> 59 minutes
21 july 9-> 20hours 0-> 59 minutes
etc etc thats why i use String and not date.
My problem is that i can't add arrayList like you did in your example for option 2 because i said that my optionPickerView will be type String and not ArrayList of String thats what i don't understand and we got the same code apparently

**Comment by xiaosong520** [comment]
@helsephas  1. You can used the linkage datatype. For details, please refer to the fourth reply , dataType :
```
var days : ArrayList = ArrayList() 
var hours : ArrayList<ArrayList> = ArrayList()
var minutes : ArrayList<ArrayList<ArrayList>> = ArrayList()
```
2. Or self modify the source code to implement this function( let option1 and option2 linked, option3 is no-linkage), dataType :
```
var days : ArrayList = ArrayList()
var hours : ArrayList<ArrayList> = ArrayList()  // depend on day
var minutes : ArrayList = ArrayList()     // 0-59
```

**Comment by helsephas** [comment]
Ye i got this from start i know i can add ArrayList like that. My problem is not that i don't understand how to use it. My problem is that i use this like you say. So i get my Arrays like you But when i use
MyOptionPickerView(String) et and i to setPicker it doesn't accept my options 2 et option 3 arrays. 

` var pickerViewDates =  MyOptionsPickerView<String>(this)
            pickerViewDates.setTitle(this.resources.getString(R.string.shopping_cart_pick_date_title))

            var now : Date = Date()

            var days : ArrayList<String> = ArrayList()
            var hours : ArrayList<ArrayList<String>> = ArrayList()
            var minutes : ArrayList<ArrayList<ArrayList<String>>> = ArrayList()

            for(cptDays in 0..30){
                val outFormat = SimpleDateFormat("EEEE")
                var dateToLastOne = Date(now.time + 86400000 * cptDays)
                val dayCode = outFormat.format(dateToLastOne).toUpperCase()
                for ( openHoursPerDay in Session.instance.currentCommand.shop.shopParameters.openHours.openHoursPerDay){
                    if(openHoursPerDay.day.code == dayCode){
                        if(openHoursPerDay.isOpen) {
                            var startTimeHours = openHoursPerDay.startTime.hours
                            var endTimeHours = openHoursPerDay.endTime.hours
                            var hoursInDay : ArrayList<String> = ArrayList()
                            for (cptHours in startTimeHours..endTimeHours) {
                                //hours.add(cptHours.toString())
                                var minutesInHour = ArrayList<String>()
                                for (cptMin in 0..59) {
                                    minutesInHour.add(cptMin.toString())
                                }
                                var minutesPerHour = ArrayList<ArrayList<String>>()
                                minutesPerHour.add(minutesInHour)
                                minutes.add(minutesPerHour)
                                hoursInDay.add(cptHours.toString())
                            }
                            hours.add(hoursInDay)
                        }
                        days.add(dateToLastOne.formatToLocalDay())
                    }
                }
            }

            pickerViewDates.setPicker(days,hours,minutes,false)
            pickerViewDates.setCyclic(true,true,true)
            pickerViewDates.show()`

**Comment by helsephas** [comment]
Oki i m sorry for all this. Because my problem was simply that : I used MyOptionsPickerView and not OptionsPickerView so i waste our both time. I m sorry for this. Thanks for all this replies and for your time. Have a nice day.
