### ISSUE TITLE
大神，请教一个私人的问题，JitPack上传的项目提示下面的错误，请问您知道怎么解决吗？

### ISSUE THREAD

**Issue by XinYiWorld** [Bigkoo/Android-PickerView#324]
* What went wrong:
A problem occurred configuring project ':CZBaseDevTool'.
> Cannot evaluate module XDbUtils : Configuration with name 'default' not found.

我的项目有2个libary，一个CZBaseDevTool，一个XDbUtils，其中前者compile了后者：    compile project(':XDbUtils')

其中CZBaseDevTool的gradle里加入了上传到Jitpack上那些必须的源码，但是XDbUtils没有加。

**Comment by xiaosong520** [comment]
@XinYiWorld 这个问题建议Google 一下吧
