### ISSUE TITLE
是否支持 两个选项，比如做那种年龄在 18-25之间这样的功能

### ISSUE THREAD

**Issue by 7caishi** [Bigkoo/Android-PickerView#325]

**Comment by xiaosong520** [comment]
@7caishi 可以实现的，不过需要注意一些事项：
1.用两级不联动选项选择器（setNpicker方法），若第二级数据小于第一级，则在点击确定时提示选择有误，并且不dismiss掉弹窗，让用户重新选择。
2.用两级联动选项选择器（setpicker方法），填充数据时的逻辑是：第二级的数据开始项大于等于第一级，如第一级第二项是2，则第二级数据从2开始。

**Comment by 7caishi** [comment]
我弄了好几天没搞定，是否有例子可以参考，万分感谢

**Comment by 7caishi** [comment]
已经解决多谢 @xiaosong520
