### ISSUE TITLE
能否第一个滚轮滚到一个城市再根据这个城市信息去服务器上查询相关信息这种

### ISSUE THREAD

**Issue by ninghaiywx** [Bigkoo/Android-PickerView#327]

**Comment by xiaosong520** [comment]
@ninghaiywx 这个控件是需要把数据一次性预设好的，因为动态请求数据会有网络延迟，会造成无法流畅切换选项的问题。

**Comment by xiaosong520** [comment]
@ninghaiywx 其实你这个需求完全可以自己通过两个RC来实现的。实现逻辑你可以参考京东它选择地区的做法。
