### ISSUE TITLE
WheelView显示条数问题

### ISSUE THREAD

**Issue by sweet2o09** [Bigkoo/Android-PickerView#329]
WheelView中有一个参数
int itemsVisible = 11;// 绘制几个条目，实际上第一项和最后一项Y轴压缩成0%了，所以可见的数目实际为9
我WheelView里面存放了一个size = 3的list,发现WheelView的高度太高了,查看了下WheelView的代码,怀疑是因为itemsVisible 参数导致WheelView高度始终是适合显示9条数据,是否能优化下,因为如果我开启循环的话,并且list.size<5的时候,WheelView显示效果就会很不理想

**Comment by sweet2o09** [comment]
希望itemsVisible 参数能开放接口或者是能获取list条目动态修改,这样就不用集成源码然后自己修改了

**Comment by sweet2o09** [comment]
还有就是3D错觉参数SCALECONTENT,这个应该是判断非中间条目是否显示3D效果的吧,是否也能够开放个接口能设置是否3D错觉,这样的话就更加灵活了
我知道您这个框架1.X版本是没3D效果的,不过我还是喜欢用你们最新的版本,谢谢!

**Comment by xiaosong520** [comment]
@sweet2o09  #297 已经在这里有回复过了，没有开放itemsVisible 接口是因为Wheel绘制的时候有偏差修正的处理，以保证item居中。**不同itemsVisible 条目**以及**不同分辨率**下的偏差情况都很难统一计算，兼容性无法保证。所以是建议通过修改Item的文字大小以及条目间距倍数来调整UI效果。如需显示其他条目数量，可自己module引入一下工程改改参数来实现。 至于普通效果，因为要改动整个控件的计算逻辑，工作量会很大，目前工作抽不出那么多的时间来重构，后续会考虑优化。若有兴趣也可以 Pull Request 我有时间会合并代码，感谢支持~
