### ISSUE TITLE
setOutSideCancelable(false)点击PickerView外面PickerView还是会消失

### ISSUE THREAD

**Issue by iamzj** [Bigkoo/Android-PickerView#333]
setOutSideCancelable()不管是true还是false都会消失

**Comment by xiaosong520** [comment]
@iamzj 麻烦详细说一下版本号，使用场景等信息，提供的信息太少了。

**Comment by iamzj** [comment]
compile 'com.contrarywind:Android-PickerView:3.2.5'
使用详情：手机华为5.0，就是进入Activity就弹出对话框，但是点击框外会消失
代码如下：
OptionsPickerView optionsPickerView = new OptionsPickerView.Builder(InventoryWarningActivity.this, new OptionsPickerView.OnOptionsSelectListener() {
    @Override
    public void onOptionsSelect(int options1, int options2, int options3, View v) {
        //代码。。。
    }
}).isDialog(true).build();
optionsPickerView.setPicker(warehouseDataBeanList);
optionsPickerView.setDialogOutSideCancelable(false);
optionsPickerView.setOnDismissListener(new OnDismissListener() {
    @Override
    public void onDismiss(Object o) {
        //代码。。。
    }
});
optionsPickerView.show();

**Comment by xiaosong520** [comment]
@iamzj setDialogOutSideCancelable 对话框模式下，使用这个方法。

**Comment by totcw** [comment]
要在build()之前调用setOutSideCancelable(false)方法,才会有效果的

**Comment by xiaosong520** [comment]
@iamzj 如上所述

**Comment by Yiwei099** [comment]
@xiaosong520 @totcw 版本4.1.9如下设置也是无效：
```
TimePickerBuilder(mContext) { date, _ ->
            //return data
            f.invoke(MyTimeUtils.date2Str(date, MyTimeUtils.HM))
        }
            .setType(booleanArrayOf(false, false, false, true, true, false)) // 默认全部显示
            .setContentTextSize(15) //滚轮文字大小
            .setOutSideCancelable(false) //点击屏幕，点在控件外部范围时，是否取消显示
            .isCyclic(false) //是否循环滚动
            .setItemVisibleCount(2)
            .setTitleColor(Color.BLACK)
            .setTextColorCenter(Color.BLACK)
            .setRangDate(startTimer, Calendar.getInstance())//起始终止年月日设定
            .setLabel("", "", "", "", "", "") //默认设置为年月日时分秒
            .isCenterLabel(false) //是否只显示中间选中项的label文字，false则每项item全部都带有label。
            .isDialog(false) //是否显示为对话框样式
            .setDate(startTimer)
            .build()
            .show()
```
