### ISSUE TITLE
地区二级联动第二级显示不出来

### ISSUE THREAD

**Issue by ShineBright2015** [Bigkoo/Android-PickerView#334]

**Comment by xiaosong520** [comment]
@ShineBright2015 请参照demo项目的示例代码来写。

**Comment by ShineBright2015** [comment]
有两级城市选择的示例吗？

**Comment by xiaosong520** [comment]
@ShineBright2015  [MainActivity.java](https://github.com/Bigkoo/Android-PickerView/blob/master/app/src/main/java/com/bigkoo/pickerviewdemo/MainActivity.java)
