### ISSUE TITLE
你好，请问怎么监听“取消”和“确定”按钮点击事件

### ISSUE THREAD

**Issue by iamzj** [Bigkoo/Android-PickerView#337]
版本：3.2.5
情景：我想点击取消就退出页面，点击确定就加载数据
发现只有setOnDismissListener

**Comment by totcw** [comment]
目前是只有点击确定会回调onTimeSelect方法

**Comment by iamzj** [comment]
我的是OptionsPickerView，不是TimePickerView，而且就一级，不联动。
大神有空时候能否加上这俩事件，以后项目也可以用

**Comment by xiaosong520** [comment]
@iamzj 你可以通过自定义布局来实现，自定义布局可以自己实现确定取消按钮的onclikelistener。
