### ISSUE TITLE
二级不联动需求

### ISSUE THREAD

**Issue by lucifer222** [Bigkoo/Android-PickerView#339]
请问二级的不联动，怎么写？我用setNPicker() 里面的参数是3个参数，而且第二个参数是List<List<>>, 这个是怎么写，我也不太懂

**Comment by xiaosong520** [comment]
@lucifer222 setNPicker() 第三个参数填null即可，参数类型都是List<T> ，不用嵌套数据。

**Comment by lucifer222** [comment]
好的，谢谢
