### ISSUE TITLE
两列时间距太宽

### ISSUE THREAD

**Issue by lucifer222** [Bigkoo/Android-PickerView#340]
两级的时候 两列之间的间距太宽，怎么调整？

**Comment by xiaosong520** [comment]
@lucifer222  [方法与参数说明（3.x版）](https://github.com/Bigkoo/Android-PickerView/wiki/%E6%96%B9%E6%B3%95%E5%90%8D%E4%B8%8E%E5%8F%82%E6%95%B0%E8%AF%B4%E6%98%8E%EF%BC%883.x%E7%89%88%E6%9C%AC%EF%BC%89)  setLineSpacingMultiplier方法

**Comment by lucifer222** [comment]
你好，刚刚试了一下，这个是行之前的间距吧，我要调整的是两列之间的间距

**Comment by xiaosong520** [comment]
@lucifer222 可以利用自定义布局改一下Wheelview控件的布局属性。
