### ISSUE TITLE
发现个问题，日联动的问题

### ISSUE THREAD

**Issue by idic779** [Bigkoo/Android-PickerView#341]
你好， 有个问题如果是时间选择器，demo中的第一个item 设置了isCyclic（true）,先选择日为01日，然后这时候滚动逐个滚动月列表，会出现日偏移的情况？

**Comment by xiaosong520** [comment]
@idic779 是这样的，因为日期和月份是关联的，不同月份下的日期总数也不同。所以会存在月份改动的时候，item位置有所改变。isCyclic只是设置循环轮播，并非不联动。

**Comment by idic779** [comment]
@xiaosong520 月份不同日期总数确实会变，情况是我先随意滑动日选择到01日，这时候滑动月，选1月01日，接着缓慢滑动其他月，会出现01日变为02 日之类的情况，不知道你那边能否复现这个情况，我试了几台手机都是

**Comment by xiaosong520** [comment]
@idic779 是会有的呀， 不循环也会有这样的情况。 你可以试一下选择2月29日，然后切换到其他月份，必然会变呀，这并不算Bug。
