### ISSUE TITLE
不能二级不联动吗

### ISSUE THREAD

**Issue by 643063150** [Bigkoo/Android-PickerView#343]
`` pvNoLinkOptions = new OptionsPickerView.Builder(this, new OptionsPickerView.OnOptionsSelectListener() {

            @Override
            public void onOptionsSelect(int options1, int options2, int options3, View v) {

                String str = "food:" + food.get(options1)
                        + "\nclothes:" + clothes.get(options2)
                        + "\ncomputer:" + computer.get(options3);

                Toast.makeText(MainActivity.this, str, Toast.LENGTH_SHORT).show();
            }
        }).build();
        pvNoLinkOptions.setPicker(food, clothes);

**Comment by 643063150** [comment]
写成这样就会崩溃 报错Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.util.List

**Comment by xiaosong520** [comment]
@643063150 请先搞清楚错误日志信息，日志已经很明显提示了是类型转换错误，setPicker需要填List类型的参数，“Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.util.List”这儿已经提示了。

**Comment by xiaosong520** [comment]
@643063150 不懂的话就下载demo参考一下使用方法，谢谢。

**Comment by 643063150** [comment]
看到了 一个是setNPicker一个是setPicker  两个方法太像了，但是这个不联通的setNPcker 好像只有一个三级不联通的方法

**Comment by xiaosong520** [comment]
@643063150  setNPcker 两级不联动的选项，第三个参数填nul即可。l

**Comment by 643063150** [comment]
好的 谢谢
