### ISSUE TITLE
时间选择初始化 失败 报空指针错误

### ISSUE THREAD

**Issue by BananaLF** [Bigkoo/Android-PickerView#344]
以gradle使用

  tvTitle = (TextView) findViewById(R.id.tvTitle);
  btnSubmit = (Button) findViewById(R.id.btnSubmit);
  btnCancel = (Button) findViewById(R.id.btnCancel);

查出findViewById 返回为null 

reBuild 一下project 就OK了 我也是醉了

**Comment by xiaosong520** [comment]
@BananaLF gradle缓存异常导致的问题
