### ISSUE TITLE
获取选中时间

### ISSUE THREAD

**Issue by xiekelin** [Bigkoo/Android-PickerView#345]
大神，在选择器停止运动时，立刻得到选中的时间，如何实现？

**Comment by xiaosong520** [comment]
@xiekelin 处理起来会稍微有点儿复杂，需要在Item切换时，实时对WheelView回调，而且回调需获取其他WheelView的选中位置（要年月日时分秒，六个WheelView其他五个都需要这么做），然后再回调传递给TimePicker。

**Comment by xiekelin** [comment]
我看了源码，发现比较难判断滑动停止。源码可能看的不够深，请问 如何判断停止事件呢？

**Comment by xiekelin** [comment]
我在 WheelView的cancelFuture一步一步回调给结果TimePicker，然后TimePicker给回activity上，可以实现了，虽然有偏差，但比较小，可以接受。

**Comment by xiaosong520** [comment]
@xiekelin 你可以参考我之前写的WheelView的源码解析篇，因为绘制文字是基于text的基线位置的，所以会有点儿偏差，对它做一个偏移量减除应该就会好很多。
