### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by eavenFan** [Bigkoo/Android-PickerView#349]
时间选择器，当只设置选择月和日时，设置为当前系统时间，最后选择完成的时间，年份一定是1990，而非我之前设置的时间年份，这样会导致，2月份的日期是不准确的

**Comment by xiaosong520** [comment]
@eavenFan 默认初始时间是1990年，你在设置时间的时候，将年份设定为当前年份即可。

**Comment by eavenFan** [comment]
@xiaosong520 已经设置过了，没有用，最后得到的是1990年加上选择的月和日

**Comment by eavenFan** [comment]
@xiaosong520 我设置的时间是2016年，选择2月29日，最后得到的结果是1990-03-1

**Comment by xiaosong520** [comment]
@eavenFan 设置当前时间那里，将年份设置为当前的年份。

**Comment by eavenFan** [comment]
@xiaosong520 没用的，我做了测试，如果我做年月日的选择的话，时间是正常的，但是我只做月日的选择的话，最后得到的时间就有问题了，年份肯定是1990年，其他都设置都不变，只是setType时这里有变化

**Comment by xiaosong520** [comment]
@eavenFan 刚测试了一下，确实存在这个问题，初步排查发现是内部setRangDate 方法逻辑没有优化好，下个版本会修复这个问题。你暂时先将 startDate 设置为当前需要显示的年份即可解决。

**Comment by eavenFan** [comment]
@xiaosong520 好的谢谢

**Comment by xiaosong520** [comment]
v3.2.6 已修正
