### ISSUE TITLE
布局问题

### ISSUE THREAD

**Issue by lucifer222** [Bigkoo/Android-PickerView#350]
<LinearLayout
        android:id="@+id/optionspicker"
        android:layout_width="fill_parent"
        android:layout_height="wrap_content"
        android:background="@android:color/white"
        android:gravity="center_horizontal"
        android:orientation="horizontal">

        <com.bigkoo.pickerview.lib.WheelView
            android:id="@+id/options1"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"/>

        <com.bigkoo.pickerview.lib.WheelView
            android:id="@+id/options2"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content" />

        <com.bigkoo.pickerview.lib.WheelView
            android:id="@+id/options3"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"/>

    </LinearLayout>

为什么我自定义布局之后，就只显示中间一列的数据，不管setNPicker()里传入几个参数，都只显示一列数据？

**Comment by xiaosong520** [comment]
@lucifer222 请参考demo检查一下代码写法，需要配置权重的。

**Comment by lucifer222** [comment]
我不想配置权重，先2列或者3列是集中在整个页面的中间位置的
