### ISSUE TITLE
设置设置间距倍数为什么只能在1.2-2.0

### ISSUE THREAD

**Issue by pricnehao** [Bigkoo/Android-PickerView#351]
设置设置间距倍数为什么只能在1.2-2.0 是不是超过这个设置就会出现问题 还是什么 因为这边ui给他的行高是比较高的  2.0 无法满足

**Comment by xiaosong520** [comment]
@pricnehao 你可以拉源码引入module自己把间距倍数的限制改改。

**Comment by pricnehao** [comment]
嗯嗯 已经改过了 但不是不知道 为什么你们必须要控制在1.2-2.0 担心 后期出现什么不适配

**Comment by xiaosong520** [comment]
@pricnehao一般情况下间距也不会超过2倍 ，此外间隔太宽了的话需要修复误差的值不太好控制。

**Comment by pricnehao** [comment]
嗯嗯 好的 谢谢
