### ISSUE TITLE
研究了两天 bug不是一般的多

### ISSUE THREAD

**Issue by f630088281** [Bigkoo/Android-PickerView#355]
╮(╯▽╰)╭  坑

**Comment by f630088281** [comment]
时间联动   比如2010-10 ----- 2017-8    从无到到无  就会出现神奇的bug

**Comment by f630088281** [comment]
我选择2016-12   然后年切换到2017   回调竟然是2017-12

**Comment by xiaosong520** [comment]
@f630088281 请认真研究之后再好好提问 issue，“2016-12 然后年切换到2017 回调竟然是2017-12” 这个只是为了避免reset浪费性能而保持持有旧的postion位置。 至于第二个，回答的有点模棱两可。
