### ISSUE TITLE
WheelView里面几个属性建议开放设置

### ISSUE THREAD

**Issue by winxinxinxin** [Bigkoo/Android-PickerView#358]
WheelView里面几个属性建议开放设置：

// 绘制几个条目，实际上第一项和最后一项Y轴压缩成0%了，所以可见的数目实际为9
    int itemsVisible = 11;
 // 半圆周长
    int halfCircumference;
    // 半径
    int radius;
//初始化默认选中项
    int initPosition;
    //选中的Item是第几个
    private int selectedItem;

**Comment by xiaosong520** [comment]
@winxinxinxin 条目只能暂定为11，详情参考这里 #329，合理搜索已有Issue来找到答案避免重复的提问 。至于其他属性，半圆周长就是Item数目*ItemHeight，半径是根据周长计算得到的。默认选中项是可以通过setSelectOptions 方法设置的。建议先看看我之前写的那篇WheelView绘制原理的博客，熟悉一下它的实现机制。

**Comment by winxinxinxin** [comment]
条件选择器的样式都是平铺的，时间选择器不能设置平铺的？
