### ISSUE TITLE
发现3.2.6的一个bug

### ISSUE THREAD

**Issue by carBigun** [Bigkoo/Android-PickerView#359]
OptionsPickerView的一个全局变量,若第一次setPicker(lists),lists.size=0时,那么接下来再次setpicker时,无论list.size=N,都不会显示正确的数据!
解决:判断若lists.size==0时,lists.add("")

**Comment by xiaosong520** [comment]
@carBigun #317 这个问题已经有回复了，建议先搜索一下是否issues是否已存在相同的问题。并且  demo 里面已经有注释提示了，在JsonDataActivity类里面。
