### ISSUE TITLE
3.2.6与软键盘冲突问题。

### ISSUE THREAD

**Issue by DizzyYang** [Bigkoo/Android-PickerView#360]
Nexus 5X

7.1.1

软键盘显示后timePickerView.show()软键盘未关闭。

**Comment by xiaosong520** [comment]
@DizzyYang 这个并不是BUG，只是系统焦点问题，你可以设置一下Activity的软键盘显示模式。或者在调用show方法时通过代码主动让软键盘隐藏起来。
