### ISSUE TITLE
当月和日都是1时，年份滑动到顶部月和日布局问题

### ISSUE THREAD

**Issue by ContainsK** [Bigkoo/Android-PickerView#363]
当月和日都是1时，年份滑动到顶部月和日布局问题。
图：
[问题截图](http://chuantu.biz/t6/10/1503041236x1929172127.png)

**Comment by xiaosong520** [comment]
@ContainsK 具体代码麻烦贴一下（起始终止时间这一块的）

**Comment by ContainsK** [comment]
@xiaosong520 问题已经解决了，确实是因为起始时间设置这一块的问题（我将“日”字段设置为0）。

**Comment by xiaosong520** [comment]
@ContainsK 好的~
