### ISSUE TITLE
只显示年月日时，label和年月日数值间隔很宽

### ISSUE THREAD

**Issue by shaochen007** [Bigkoo/Android-PickerView#372]
当控件只显示年、月、日时，因label是靠右显示的，导致数值和label间隔很宽，怎么改成靠左显示？

**Comment by xiaosong520** [comment]
@shaochen007 可参考这个issue #220 ， 也可以通过自定义布局自行添加TextView显示单位。

**Comment by xiaosong520** [comment]
#272 这个问题也有回答

**Comment by daleiyinsi** [comment]
如何只显示年月日，没有看到方法，求教

**Comment by xiaosong520** [comment]
setType()方法，setType(new boolean[]{true, true, true, false, false, false})  分别代表年月日时分秒的显示与否。
