### ISSUE TITLE
能否做成横向滑动

### ISSUE THREAD

**Issue by KenLiuz** [Bigkoo/Android-PickerView#390]
最近有个新项目需求是做成横向滑动小图片，感觉效果跟这个差不多，但是要做成横向怎么处理？

**Comment by xiaosong520** [comment]
@KenLiuz 有类似的库，可自行在GitHub查找。

**Comment by KenLiuz** [comment]
您好，这个我已经从昨天找到现在了，没找到我想要的，如果您有资源的话或者您有收藏类似的代码的话能不能提供一下呢

**Comment by xiaosong520** [comment]
@KenLiuz HorizontalPicker
