### ISSUE TITLE
省市区三级联动异步支持

### ISSUE THREAD

**Issue by LayGit** [Bigkoo/Android-PickerView#393]
目前的三级联动好像是不支持异步加载的，是否有支持的计划？

**Comment by xiaosong520** [comment]
@LayGit 是指动态请求数据吗？ 动态请求网络会因为延时性造成滑动不流畅，及Loading等待，卡顿等问题，暂时没有考虑。

**Comment by xiaosong520** [comment]
@LayGit 或许也可以通过三级不联动的方式来实现异步请求的逻辑。只是需要稍加修改源码实现实时回调。
