### ISSUE TITLE
请问如何修改分割线中间的背景颜色？

### ISSUE THREAD

**Issue by m2kl1m** [Bigkoo/Android-PickerView#398]
![ng5q 1xfi4d rb q 2 tu](https://user-images.githubusercontent.com/25895481/30727190-4af08f84-9f82-11e7-97ad-b3bcbcb17b41.png)
期待您的回复

**Comment by xiaosong520** [comment]
@m2kl1m #332 暂时没有这个设置选项，可以自行改一下代码添加。 在WheelView类里面绘制一个选中项背景色。
