### ISSUE TITLE
3.2.6版本不能设置类型呀 只能用默认的数组 怎么自定义

### ISSUE THREAD

**Issue by hudafei1225** [Bigkoo/Android-PickerView#414]
setType(boolean[] timeType)
之前的setType(TYPE)是可以设置的

**Comment by xiaosong520** [comment]
@hudafei1225 因为之前那种枚举的办法会导致漏了一些组合项，所以通过数组控制每个选项的显示与否了。

**Comment by hudafei1225** [comment]
设置了日期范围  但现在有需求就是 当前日期之前的日期不可选择  请问有暴露出来的方法吗

**Comment by xiaosong520** [comment]
@hudafei1225 setRangDate 方法，具体可参考demo。

**Comment by hudafei1225** [comment]
多谢您了
