### ISSUE TITLE
类似这样的样式好像不能实现

### ISSUE THREAD

**Issue by keyescgm** [Bigkoo/Android-PickerView#416]
![image](https://user-images.githubusercontent.com/9543572/32213183-3594dacc-be55-11e7-85a8-4aae847eb4ce.png)

**Comment by xiaosong520** [comment]
@keyescgm 可以实现，只是需要在现有TimePicker代码上面自行拓展。

**Comment by keyescgm** [comment]
如果拿你源代码做修改，下次就不能更新你的版本了~~

**Comment by keyescgm** [comment]
能给点思路吗？急需，我正在下载你的源代码修改呢，这样感觉不好，下次没法用你的最新版

**Comment by xiaosong520** [comment]
@keyescgm 要实现你上面的需求，目前暂时没有什么其他更好的办法。或许，可以跟产品沟通，说服产品保持现有的逻辑。
