### ISSUE TITLE
设置isDialog(true)的时候再设置setDialogOutSideCancelable(true)并没有效果

### ISSUE THREAD

**Issue by quanquanams** [Bigkoo/Android-PickerView#420]
设置isDialog(true)的时候再设置setDialogOutSideCancelable(true)并没有效果
因为BasePickerView中,只设置了mDialog.setCancelable(cancelable),这个是点击返回键关闭dialog
要设置点击屏幕空白处禁止返回需要mDialog.setCanceledOnTouchOutside(cancelable);
望修改@xiaosong520

**Comment by xiaosong520** [comment]
@quanquanams  Thanks

**Comment by xiaosong520** [comment]
@quanquanams 排查发现，原因是build之后调用setOutSideCancelable方法，没有重新设置dialog的cancelable导致失效的。 现版本你可以在build之前调用setOutSideCancelable即可生效。另外，build之后再调用设置失效的问题我也修复了，代码将在下个版本生效。

**Comment by quanquanams** [comment]
@xiaosong520 谢谢!效率超高
