### ISSUE TITLE
英文时取消(CANCEL)，确定(SUBMIT) 文字异样

### ISSUE THREAD

**Issue by CL-window** [Bigkoo/Android-PickerView#421]
include_pickerview_toolbar.xml
英文时使用：Cancel,Submit， 但是使用的是Button,目前显示出来全是大写字母，需要新增 android:textAllCaps="false"，  改完之后如下
<Button
        android:id="@+id/btnCancel"
        android:textAllCaps="false"
        android:layout_width="wrap_content"
        android:layout_height="match_parent"
        android:background="@android:color/transparent"
        android:gravity="left|center_vertical"
        android:paddingLeft="@dimen/pickerview_topbar_padding"
        android:text="@string/pickerview_cancel"
        android:textColor="@drawable/selector_pickerview_btn"
        android:textSize="@dimen/pickerview_topbar_btn_textsize" />

确定取消都需要添加，望下个版本修复

**Comment by xiaosong520** [comment]
@CL-window 这个是自身APP适配的问题。英文语言本身就需要显示英文的。可以通过在APP module 覆盖一下values值即可。
