### ISSUE TITLE
滚动监听，直接使用到布局文件中

### ISSUE THREAD

**Issue by chengkaizone** [Bigkoo/Android-PickerView#431]
滚动轮没有添加滚动停止选中或者点击事件的回调，这个没有办法直接嵌入到布局中，iOS是可以直接添加到布局的，希望可以实现这个功能

**Comment by xiaosong520** [comment]
@chengkaizone 请参照demo，里面有提供支持直接嵌入布局的示例。一级列表可直接引入wheelview类，里面有带了滚动停止的回调，但多级滚动停止的回调目前没有支持。
