### ISSUE TITLE
OptionsPickerView关于数据加载

### ISSUE THREAD

**Issue by VincentYD** [Bigkoo/Android-PickerView#435]
你好,OptionsPickerView 设置了联动时一二三级数据都是要同时设置上去的,假设有这样的需要(不能一次性拿到所有数据),就是我选择了一级的某个数据后,必须联网请求才能拿到二级数据,然后三级数据也是根据二级数据去请求服务器,这个要怎么去实现?

**Comment by xiaosong520** [comment]
@VincentYD 类似这样分级多次请求数据的需求，建议参考微信或者京东的逻辑，实在需要PickerView的选择效果，建议用不联动选项，稍加修改源码自行扩展逻辑。有疑问可查阅Wiki - 常见问题 ：https://github.com/Bigkoo/Android-PickerView/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98
