### ISSUE TITLE
省市区怎么记住上次记住的地址

### ISSUE THREAD

**Issue by douya40** [Bigkoo/Android-PickerView#445]
省市区怎么记住上次记住的地址

**Comment by xiaosong520** [comment]
@douya40 [Wiki 方法及参数说明]( https://github.com/Bigkoo/Android-PickerView/wiki/%E6%96%B9%E6%B3%95%E5%90%8D%E4%B8%8E%E5%8F%82%E6%95%B0%E8%AF%B4%E6%98%8E%EF%BC%883.x%E7%89%88%E6%9C%AC%EF%BC%89) 这里有API文档，可以自行查找一下自己所需要的哦~
