### ISSUE TITLE
  这个控件有没有属性  设置不能选择到今天以后的日期  比喻今天是2017 12 14 ，   2017 12 15就不能滑到哪里去。

### ISSUE THREAD

**Issue by wang709693972wei** [Bigkoo/Android-PickerView#449]
这个控件有没有属性  设置不能选择到今天以后的日期    比喻今天是2017 12 14 ，   2017 12 15就不能滑到哪里去。

**Comment by xiaosong520** [comment]
@wang709693972wei  setRangDate(startDate,endDate)//起始终止年月日设定。
