### ISSUE TITLE
运行TimePickView出现空指针异常

### ISSUE THREAD

**Issue by bozaixing** [Bigkoo/Android-PickerView#454]
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.LinearLayout.setBackgroundColor(int)' on a null object reference

**Comment by bozaixing** [comment]
已经解决了。

**Comment by xiaosong520** [comment]
@bozaixing 好的~ 那我关掉这个问题了

**Comment by YunniWeng** [comment]
怎么解决的呀？不说一声？？？？

**Comment by chengh2016** [comment]
怎么解决的，我也遇到了，初始化的时候

**Comment by SaltedFishkk** [comment]
怎么解决的???????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????

**Comment by gaoqianZ** [comment]
求问这个问题怎么解决

**Comment by bozaixing** [comment]
你QQ多少？我加你。&nbsp;

Love life, facing the sea, chun nuanhua leaves!
 

&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "notifications"<notifications@github.com&gt;; 
发送时间: 2019年12月18日(星期三) 晚上7:53
收件人: "Bigkoo/Android-PickerView"<Android-PickerView@noreply.github.com&gt;; 
抄送: "伯在兴"<654152983@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [Bigkoo/Android-PickerView] 运行TimePickView出现空指针异常 (#454)



求问这个问题怎么解决

**Comment by Fishbonelsy** [comment]
求问怎么解决的？
