### ISSUE TITLE
TimePickerView 有监听滚动获得相应时间数据的方法吗

### ISSUE THREAD

**Issue by zhanhon** [Bigkoo/Android-PickerView#470]

**Comment by xiaosong520** [comment]
@zhanhon WheelTime 里面有设置了监听回调，但这仅是监听WheelView的，若需要在切换选项时，将date 数据回调，则需要在 WheelTime 类里面 年月日 的OnItemSelectedListener 回调处，再调用TimePickerView 的onTimeSelect方法。

**Comment by 80998062** [comment]
问下为什么不直接加入这个回调,感觉这个蛮有必要的
PS: 我在使用过程中也遇到了这个需求

**Comment by xiaosong520** [comment]
@80998062 新版本已支持设置，具体请参看WIKI文档。
