### ISSUE TITLE
地址三级级联选择的问题？没有判断第二级是空的情况

### ISSUE THREAD

**Issue by niyaode** [Bigkoo/Android-PickerView#476]
我的第二级是Bean对象 ，他实现IPickerViewData 接口，在二级地址为空的情况下就报空指针，
我试图在二级循环时做判断，把options2Items 的数据结构new出来报错java.lang.IndexOutOfBoundsException: Index: 0, Size: 0。
我又试图在二级地址为空的情况把源数据options1Items （我用他做源数据）下标位置替换掉
list.add（index，Bean）；
java.lang.ArrayIndexOutOfBoundsException: length=0; index=-1

----------------------------------------
    private ArrayList<JsonBean> options1Items = new ArrayList<>();
    private ArrayList<ArrayList<String>> options2Items = new ArrayList<>();
    private ArrayList<ArrayList<ArrayList<String>>> options3Items = new ArrayList<>();

 pvOptions.setPicker(options1Items, options2Items,options3Items);//三级选择器

**Comment by xiaosong520** [comment]
@niyaode 没有数据的时候添加一个空字符串即可。 具体可参考demo工程里面的示例代码。
