### ISSUE TITLE
OptionsPickerView里面item重名点击反馈始终是第一个item的index

### ISSUE THREAD

**Issue by luciandun** [Bigkoo/Android-PickerView#482]
OptionsPickerView传入一个string列表作为item内容，如：“AAA”,"BBB","CCC","DDD","BBB",选中第一个BBB，返回的index是1，选中第二个BBB，返回的index还是1，求修复~

**Comment by xiaosong520** [comment]
@luciandun 由于代码里面有支持循环模式的缘故，不能直接通过 wheelView 类里的index 位置来获取position值。因此代码里获取 position 位置是 通过indexof 方法来查找的，这样会获取到最先查找到的index 索引值，也就是出现了上面所述问题。不过一般情况下，选择器里面是不需要出现重复value 值的。
因此若实在需要显示重复Value，并能区分出来，现阶段需要自己拓展一下，改动源码里面获取索引的逻辑。这个问题后续版本会考虑寻找更合理的实现方式去优化~

**Comment by xiaosong520** [comment]
@luciandun  V4.1.1 版本已修复并优化该问题了。
