### ISSUE TITLE
关于英文显示问题#

### ISSUE THREAD

**Issue by q460468765** [Bigkoo/Android-PickerView#491]
国外的项目，需要显示英文，Button按钮默认的风格会把小写字母变成大写，以gradle方式导入的话那个“Submit”和“Cancel”按钮都是大写的，一个很小的问题缺只能以Module的形式导入自己修改，可以改一下。

**Comment by xiaosong520** [comment]
@q460468765 后续4.0版本会优化一下~

**Comment by xiaosong520** [comment]
@q460468765   在APP主题style 里面设置<item name="textAllCaps">false</item> 应该可以全局避免被自动转换为大写。
