### ISSUE TITLE
自定义view显示时间小时和分钟第一个字段一直为3，应该是0

### ISSUE THREAD

**Issue by w1570187062** [Bigkoo/Android-PickerView#492]
![img_1690](https://user-images.githubusercontent.com/10276096/35506054-077260c8-0523-11e8-9ce0-cbbbb5422e2a.JPG)
使用方式如下：
        Calendar selectedDate = Calendar.getInstance();//系统当前时间
        Calendar startDate = Calendar.getInstance();
        startDate.set(2014, 1, 23);
        Calendar endDate = Calendar.getInstance();
        endDate.set(2027, 2, 28);
        //时间选择器 ，自定义布局
        pvCustomTime = new TimePickerView.Builder(mContext, (date, v) -> {
     
        })
                .isDialog(true)
                .setDate(selectedDate)
                .setLayoutRes(R.layout.dialog_set_time, v -> {
                    TextView tvSubmit = v.findViewById(R.id.btnSure);
                    TextView tvCancel = v.findViewById(R.id.btnCancal);
                    tvSubmit.setOnClickListener(v1 -> {
                        pvCustomTime.returnData();
                        pvCustomTime.dismiss();
                        //隐藏下方虚拟按键
                        UIUtil.hideNavigation(getActivity());
                    });
                    tvCancel.setOnClickListener(v12 -> {
                        pvCustomTime.dismiss();
                        //隐藏下方虚拟按键
                        UIUtil.hideNavigation(getActivity());
                    });
                })
                .setContentSize(25)
                .setDividerType(WheelView.DividerType.WRAP)
                .setOutSideCancelable(false)
                .setType(new boolean[]{false, false, false, true, true, false})
                .setLineSpacingMultiplier(1.2f)
                .setTextXOffset(0, 0, 0, 40, 0, -40)
                .isCenterLabel(false) //是否只显示中间选中项的label文字，false则每项item全部都带有label
                .setDividerColor(Color.parseColor("#2f3032"))
                .setBgColor(Color.parseColor("#2f3032"))
                .setTextColorCenter(Color.parseColor("#1eac29"))
                .build();
        pvCustomTime.show();

**Comment by xiaosong520** [comment]
@w1570187062  我这边复制上述代码，运行显示正常，你使用的PickerView版本号是多少?  有没有尝试用其他手机运行？

**Comment by w1570187062** [comment]
@xiaosong520 你好，换了个虚拟机跑了一下正常了，但是实线颜色设置和背景色一致，但是好像有些不同。但是软件只能跑在出问题的设备上啊，这咋整。。。
![image](https://user-images.githubusercontent.com/10276096/35510053-7c604306-0531-11e8-8d10-e857d3424f06.png)

**Comment by w1570187062** [comment]
@xiaosong520 你好，应该是自定义的xml里面LinearLayout高度不够导致的，图片中的布局是RelativeLayout，包含pickerView的LinearLayout居中，两条线以LinearLayout为焦点Margin的，现在把两条线marginTop，marginBottom可以了，没有动java代码部分，谢谢。

**Comment by w1570187062** [comment]
![12345](https://user-images.githubusercontent.com/10276096/35542926-71821114-059d-11e8-9304-3919a653910c.png)

**Comment by xiaosong520** [comment]
@w1570187062 好的~ 解决了问题就好。
