### ISSUE TITLE
滑到边界时卡顿

### ISSUE THREAD

**Issue by 13483865820** [Bigkoo/Android-PickerView#501]
// 边界处理。
                if (!isLoop) {
                    float top = -initPosition * itemHeight;
                    float bottom = (adapter.getItemsCount() - 1 - initPosition) * itemHeight;

                    if (totalScrollY - itemHeight * 0.25 < top) {
                        top = totalScrollY - dy;

                    } else if (totalScrollY + itemHeight * 0.25 > bottom) {
                        bottom = totalScrollY - dy;
                    }

                    if (totalScrollY < top) {
                        totalScrollY = (int) top;
                    } else if (totalScrollY > bottom) {
                        totalScrollY = (int) bottom;
                    }
                }
大神，以上代码导致在滑到第一item和最后一个item卡主（手指不抬起）
请问代码作用是什么

**Comment by xiaosong520** [comment]
@13483865820  用于防止Item滑出可选范围。

**Comment by 13483865820** [comment]
但是版主这样做在手指不抬起的情况下滑动到第一和最后的item时会有明显的卡顿感，
我做了以下修改，楼主可以尝试一下，我测试了下没有卡顿感了

                float ratio = 0.5f;

                // 边界处理。
                if (!isLoop) {
                    float top = -initPosition * itemHeight;
                    float bottom = (adapter.getItemsCount() - 1 - initPosition) * itemHeight;

                    if (totalScrollY + itemHeight * ratio < top) {
                        top = totalScrollY - dy;

                    } else if (totalScrollY - itemHeight * ratio > bottom) {
                        bottom = totalScrollY - dy;
                    }

                    if (totalScrollY < top) {
                        totalScrollY = (int) top;
                    } else if (totalScrollY > bottom) {
                        totalScrollY = (int) bottom;
                    }
                }

**Comment by xiaosong520** [comment]
@13483865820 嗯嗯，根据 item 长度换算的周长值是有一些偏差的，所以临界值会有点误差，我后续会再调整一下。
