### ISSUE TITLE
有虚拟按键的手机，打开时会和虚拟按键重合

### ISSUE THREAD

**Issue by 2318423730** [Bigkoo/Android-PickerView#509]

**Comment by xiaosong520** [comment]
@2318423730 setDecorView 方法应该可以解决问题。具体可参考wiki。

**Comment by xiaosong520** [comment]
@wang709693972wei 改成dialog 样式，设置底部弹出可解决问题，具体可参考4.1.3版本的demo代码。

**Comment by 2318423730** [comment]
布局里面多加一个布局就是了，专门用来setDecorView

**Comment by pepyspeng** [comment]
@xiaosong520 如果设置成dialog样式，setOutSideColor()，方法就失效了。
