### ISSUE TITLE
建议将确定和取消的监听开放接口出来

### ISSUE THREAD

**Issue by ZhuDaiLei** [Bigkoo/Android-PickerView#511]
因为有时候点击确定或者取消，并不仅仅是dismiss就好了，可能想插入更多的逻辑；现在这样我判断控件是否点击了取消，只有通过setOnDismissListener来实现，但是并不能满足我的需求，建议大大开放接口出来；

**Comment by xiaosong520** [comment]
@ZhuDaiLei 自定义布局 可直接设置点击事件监听。
