### ISSUE TITLE
setRangeDate中的问题

### ISSUE THREAD

**Issue by endrol** [Bigkoo/Android-PickerView#524]
setRangeDate(Calendar startDate, Calendar endDate)
我需要一个startDate是现在的选择器，能把startDate赋为Calendar.getInstance(),但对于endDate，比如我只想在之后的一个小时中选择，这该怎么办呢？
没有找到返回值为Calendar类型的函数

**Comment by xiaosong520** [comment]
@endrol 封装的时间选择器，目前只支持限制年月日的范围。若需要选择小时的范围，需自行扩展。
