### ISSUE TITLE
setSubmitText有Bug

### ISSUE THREAD

**Issue by AntLeh** [Bigkoo/Android-PickerView#525]
在OptionsPickerBuilder當中設定 .setSubmitText("Sure") 沒有作用,看了程式碼發現
.setSubmitText() 與 .setCancelTest() 都對Cancel做設定了。

//===source code=======

    public OptionsPickerBuilder setSubmitText(String textContentCancel) {
        mPickerOptions.textContentCancel = textContentCancel;
        return this;
    }

    public OptionsPickerBuilder setCancelText(String textContentCancel) {
        mPickerOptions.textContentCancel = textContentCancel;
        return this;
    }

**Comment by xiaosong520** [comment]
@AntLeh  thanks

**Comment by xiaosong520** [comment]
@AntLeh v4.0.2版本已发布，修复了该问题。
