### ISSUE TITLE
最新版本4.0.2依赖问题，编译不通过，作者有试过吗？

### ISSUE THREAD

**Issue by devxj** [Bigkoo/Android-PickerView#526]
RT,4.0.1版本是好的

**Comment by xiaosong520** [comment]
@devxj  wheelview 依赖挂掉了，请稍等，我稍后再上传一遍~

**Comment by xiaosong520** [comment]
@devxj 4.0.2版本 的wheelview 基础库依赖打包有点问题，没依赖上，刚重新打包了一下，为了防止本地缓存问题，改了一下版本名， 4.1.0版本，试试应该可以了。

**Comment by devxj** [comment]
@xiaosong520 OK

**Comment by ZhouBey** [comment]
有出现这个问题了

**Comment by ZhouBey** [comment]
又出现这个问题了
