### ISSUE TITLE
设置2级无联动时，设置默认选中项不好使 setSelectOptions

### ISSUE THREAD

**Issue by mingzaizai** [Bigkoo/Android-PickerView#528]
设置2级无联动时setNPicker，设置默认选中项不好使 setSelectOptions，
第一种方式： .setSelectOptions(2,2)  
                     .build();

第二种方式： pvOptions.setSelectOptions(2,2);
两种方式都不好使。
通过setPicker设置一级，这个好使.

**Comment by xiaosong520** [comment]
@mingzaizai 感谢反馈，下班后会排查一下原因。

**Comment by xiaosong520** [comment]
@mingzaizai v4.1.1版本 已修复
