### ISSUE TITLE
底部弹出的条件选择器，使用dialog模式宽没有充满屏幕

### ISSUE THREAD

**Issue by cancanw** [Bigkoo/Android-PickerView#553]

**Comment by xiaosong520** [comment]
@cancanw 修改一下dialog的样式为全屏模式即可，xml代码里面的那个style 复写一份。

**Comment by cancanw** [comment]
<item name="android:windowFullscreen">true</item>             你说的是这个属性，给pickview里面的style里面的custom_dialog2设置么？试的不管用额
