### ISSUE TITLE
你好，请问在fragment的adapter中，如何设置setDecorView（）呢，华为手机底部导航栏沉浸怎么解决，谢谢

### ISSUE THREAD

**Issue by Lavned** [Bigkoo/Android-PickerView#572]
你好，请问在fragment的adapter中，如何设置setDecorView（）呢，华为手机底部导航栏沉浸怎么解决，谢谢

**Comment by xiaosong520** [comment]
@Lavned  https://github.com/Bigkoo/Android-PickerView/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98  参考 常见问题Q5
