### ISSUE TITLE
setPicker 报异常Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference

### ISSUE THREAD

**Issue by Q3B0** [Bigkoo/Android-PickerView#576]
measureTextWidthHeight中
String s1 = getContentText(adapter.getItem(i)); 为null
但是 adapter中items[i] 不是null
原因暂未找到
建议添加s1非空检测

**Comment by sshuai** [comment]
我的解决办法：implements IPickerViewData, Serializable 
 private String name = "";
    private String id;
    private List<NextDataBean> nextData;

    @Override
    public String getPickerViewText() {
        return name;
    }

name设置一个默认“”
