### ISSUE TITLE
省城市条件选择，设置循环滚动，报角标越界异常，运行的是你的demo

### ISSUE THREAD

**Issue by qq45119626FangZhi** [Bigkoo/Android-PickerView#589]
![error](https://user-images.githubusercontent.com/23535357/40964681-4c65368c-68de-11e8-9ef7-3412699f714d.png)

**Comment by qq45119626FangZhi** [comment]
![Uploading error.png…]()

**Comment by qq45119626FangZhi** [comment]
希望作者尽快帮忙修复

**Comment by xiaosong520** [comment]
@qq45119626FangZhi   香港这个选项的第三级item没有数据导致的，建议自行添加一个空串的item填充以免误判。

**Comment by qq45119626FangZhi** [comment]
![error1](https://user-images.githubusercontent.com/23535357/40974447-2689927a-68fa-11e8-892f-04c156f200cf.png)
这里明明有数据的呀。

**Comment by qq45119626FangZhi** [comment]
麻烦看一下我下午改的，目前没发现问题。
![error2](https://user-images.githubusercontent.com/23535357/40974973-f46d3664-68fb-11e8-9902-177e166ff614.png)
![error3](https://user-images.githubusercontent.com/23535357/40974976-f53c82d4-68fb-11e8-9cdb-bb495d766fbf.png)

**Comment by xiaosong520** [comment]
@qq45119626FangZhi 好的，会抽时间review 一下代码，感谢支持。

**Comment by xiaosong520** [comment]
@qq45119626FangZhi  该bug 原因是在设置循环滚动模式时，没有对WheelView的getCurrentItem 方法的index值做安全校验，现已修复 。v4.1.4新版本可以使用了。

**Comment by qq45119626FangZhi** [comment]
谢谢作者
