### ISSUE TITLE
怎么设置startDate从当前的年月日开始？

### ISSUE THREAD

**Issue by xiaming5368** [Bigkoo/Android-PickerView#599]
我通过调用Calendar，获取当前的年、月、日，然后设置给startDate。但是最后运行的时候，默认还是从1900开始的，请问怎么设置起始日期为当前的年月日。

**Comment by xiaosong520** [comment]
@xiaming5368 可参考 demo 项目。

**Comment by marren06** [comment]
demo 没有介绍啊
