### ISSUE TITLE
华为虚拟按键手机上 虚拟导航栏遮盖 时间选择器 

### ISSUE THREAD

**Issue by ximencx** [Bigkoo/Android-PickerView#615]
框架版本：4.0.3
3.x系列没遇到，bug原因还未找到

**Comment by hy201314179** [comment]
Q5. 如何解决虚拟按键挡住PickerView？
解决办法：

 .setDecorView((ViewGroup) getWindow().getDecorView().findViewById(android.R.id.content))
 .build
setDecorView（）传递的参数可以是自己页面中的ViewGroup来指定PickerView的父控件（即被添加到哪个控件去）。

**Comment by ximencx** [comment]
大佬 收到你的邮件晚了点，看了源码总觉得添加decorview的方式不大好。
不过个人已经另一种方式实现了自己想要的效果：
即新建个dialogfragment，oncreatview时从大佬的日期选择器类中拿到  设置好的rootview，然后reture给fdialog，这样就可以把fragment按照实际组合了。
