### ISSUE TITLE
Prevent label from being part of list - how ?

### ISSUE THREAD

**Issue by abiemann** [Bigkoo/Android-PickerView#628]
Hi - in the screenshot, how to prevent the label from showing as part of the list?

https://drive.google.com/open?id=1EprwJ48p5Ojoia7QXG36wIe1x0tmd7cz

I don't want the text in the red areas.
I only want the numbers in the list.

How can it be done ?

Thank you.

**Comment by xiaosong520** [comment]
@abiemann 

step one :    
```java
.isCenterLabel(true)
.build();
```

step two:  
In your custom layout  datepicker.xml, you can add margin or padding attributes，or  weight attributes , use it to adjust the UI， for example:

```java
    android:paddingLeft="20dp"
    android:paddingRight="20dp"
```
hope these can help you.

**Comment by abiemann** [comment]
thank you.

`.isCenterLabel(true) `
was most important. But it changed the label layout. So, like you recommended I used `android:layout_weight` to balance the individual WheelView. It was not very easy. It would be better if WheelView had a center gravity option.

thank you for your help.
