### ISSUE TITLE
com.contrarywind.view.WheelView#getContentText性能优化

### ISSUE THREAD

**Issue by CNGitGuy** [Bigkoo/Android-PickerView#650]
没有优化com.contrarywind.view.WheelView#getContentText性能的时候，时间选择器渲染出现严重卡顿。优化只会初步解决卡顿问题。

优化后getContentText()性能提升500+%

原始getContentText()↓↓↓：
    /**
     * 获取所显示的数据源
     *
     * @param item data resource
     * @return 对应显示的字符串
     */
    private String getContentText(Object item) {
        if (item == null) {
            return "";
        } else if (item instanceof IPickerViewData) {
            return ((IPickerViewData) item).getPickerViewText();
        } else if (item instanceof Integer) {
            //如果为整形则最少保留两位数.
            return String.format(Locale.getDefault(), "%02d", (int) item);
        }
        return item.toString();
    }

性能优化后↓↓↓：
    /**
     * 获取所显示的数据源
     *
     * @param item data resource
     * @return 对应显示的字符串
     */
    private String getContentText(Object item) {
        if (item == null) {
            return "";
        } else if (item instanceof IPickerViewData) {
            return ((IPickerViewData) item).getPickerViewText();
        } else if (item instanceof Integer) {
            //如果为整形则最少保留两位数.
            return getFixNum ((int) item);
        }
        return item.toString();
    }

    private String getFixNum(int timeNum) {
        return timeNum >= 0 && timeNum < 10 ? TIME_NUM[timeNum] : String.valueOf(timeNum);
    }

    private static final String[] TIME_NUM = {"00", "01", "02", "03", "04", "05",
            "06", "07", "08", "09"};

**Comment by xiaosong520** [comment]
@CNGitGuy  Good job
