### ISSUE TITLE
条件选择器加了.isDialog(true)之后不能宽度充满屏幕

### ISSUE THREAD

**Issue by cancanw** [Bigkoo/Android-PickerView#653]
条件选择器加了.isDialog(true)之后不能宽度充满屏幕。
 并且试了加下面这些代码也不行，怎么破？
Dialog mDialog = pvOptions.getDialog();
        if (mDialog != null) {
            FrameLayout.LayoutParams params = new FrameLayout.LayoutParams(
                    ViewGroup.LayoutParams.MATCH_PARENT,
                    ViewGroup.LayoutParams.WRAP_CONTENT,
                    Gravity.BOTTOM);

            params.leftMargin = 0;
            params.rightMargin = 0;
            pvOptions.getDialogContainerLayout().setLayoutParams(params);

            Window dialogWindow = mDialog.getWindow();
            if (dialogWindow != null) {
                dialogWindow.setWindowAnimations(com.bigkoo.pickerview.R.style.picker_view_slide_anim);//修改动画样式
                dialogWindow.setGravity(Gravity.BOTTOM);//改成Bottom,底部显示
            }
        }

**Comment by cancanw** [comment]
呃呃，已解决。。。
 Dialog mDialog = optionsPickerView.getDialog();
        if (mDialog != null) {
            FrameLayout.LayoutParams params = new FrameLayout.LayoutParams(
                    Utils.getScreenWidth(context),//这块写成获取到的屏幕的宽就ok
                    ViewGroup.LayoutParams.WRAP_CONTENT,
                    Gravity.BOTTOM);

            params.leftMargin = 0;
            params.rightMargin = 0;
            optionsPickerView.getDialogContainerLayout().setLayoutParams(params);

            Window dialogWindow = mDialog.getWindow();
            if (dialogWindow != null) {
                dialogWindow.setWindowAnimations(com.bigkoo.pickerview.R.style.picker_view_slide_anim);//修改动画样式
                dialogWindow.setGravity(Gravity.BOTTOM);//改成Bottom,底部显示
            }
        }

**Comment by cbuemc** [comment]
> 呃呃，已解决。。。
> Dialog mDialog = optionsPickerView.getDialog();
> if (mDialog != null) {
> FrameLayout.LayoutParams params = new FrameLayout.LayoutParams(
> Utils.getScreenWidth(context),//这块写成获取到的屏幕的宽就ok
> ViewGroup.LayoutParams.WRAP_CONTENT,
> Gravity.BOTTOM);
> 
> ```
>         params.leftMargin = 0;
>         params.rightMargin = 0;
>         optionsPickerView.getDialogContainerLayout().setLayoutParams(params);
> 
>         Window dialogWindow = mDialog.getWindow();
>         if (dialogWindow != null) {
>             dialogWindow.setWindowAnimations(com.bigkoo.pickerview.R.style.picker_view_slide_anim);//修改动画样式
>             dialogWindow.setGravity(Gravity.BOTTOM);//改成Bottom,底部显示
>         }
>     }
> ```

用了你的方式，并不能解决问题，有些机型会出现左右两边显示不全的情况

**Comment by rcj60560** [comment]
@cbuemc  请问你这个问题解决了吗 部分机型底部左右没填充满的情况

**Comment by cancanw** [comment]
> @cbuemc 请问你这个问题解决了吗 部分机型底部左右没填充满的情况

只用了上面的方法，其他情况没遇到就不知道了。。。

**Comment by rcj60560** [comment]
@cancanw  我的魅族测试机 底部还是会有左右空白 设置了Utils.getScreenWidth(context)

**Comment by june5753** [comment]
@cbuemc 我用红米NOTE 5A 测试后也 出现同样的问题 左右有空白，设置宽度为Utils.getScreenWidth(context)或
FrameLayout.LayoutParams.MATCH_PARENT都会有空白，深入源码后 分析到 设置为isDialog(true)后，关键代码如下：
   //设置对话框 默认左右间距屏幕30
            params.leftMargin = 30;
            params.rightMargin = 30;
            contentContainer.setLayoutParams(params);
于是，在程序中设置
               params.leftMargin = 0
                params.rightMargin = 0
仍然有空白。
完成代码如下：（kotlin版）
       optionsPickerView.dialog?.let {
            optionsPickerView.dialogContainerLayout.layoutParams = FrameLayout.LayoutParams(
                //第一个数据设置为dialog时 左右会有距离
//               或 FrameLayout.LayoutParams.MATCH_PARENT,
                Utils.getScreenWidth(context)
                FrameLayout.LayoutParams.WRAP_CONTENT, Gravity.BOTTOM).also { params ->
                params.leftMargin = 0
                params.rightMargin = 0
            }
不知能解决这个适配问题不？

**Comment by TaylorKunZhang** [comment]
修改window的属性可以解决这个问题。
```kotlin
// 去除设置的margin
pvTime.dialogContainerLayout.layoutParams = FrameLayout.LayoutParams(
        FrameLayout.LayoutParams.MATCH_PARENT,
        FrameLayout.LayoutParams.WRAP_CONTENT, Gravity.BOTTOM).also {
    it.leftMargin = 0
    it.rightMargin = 0
}

// 解决部分手机上dialog左右有间距，宽度不能铺满屏幕的问题
pvTime.dialog.window?.let {
    val lp = it.attributes
    lp.width = WindowManager.LayoutParams.MATCH_PARENT
    lp.height = WindowManager.LayoutParams.WRAP_CONTENT
    it.attributes = lp
}
```
