### ISSUE TITLE
关于源码中的一个画面偏移计算的问题

### ISSUE THREAD

**Issue by GodRuiCollection** [Bigkoo/Android-PickerView#654]
WheelView的onDraw方法里有个计算translate的部分:
float translateY = (float) (radius - Math.cos(radian) * radius - (Math.sin(radian) * maxTextHeight) / 2D);
其中 (Math.sin(radian) * maxTextHeight) / 2D 是什么意思...算的是什么?

**Comment by xiaosong520** [comment]
@GodRuiCollection 可以参考这篇博客看一下: [Android-PickerView系列之源码解析篇（二）](https://blog.csdn.net/qq_22393017/article/details/59488906)

**Comment by GodRuiCollection** [comment]
@xiaosong520 谢谢~
