### ISSUE TITLE
时间选择器是否可以添加时间限制功能

### ISSUE THREAD

**Issue by qianshengta** [Bigkoo/Android-PickerView#657]
时间选择器是否可以添加时间限制功能，比如我规定不得早于或晚于规定的时间，最好是不在规定时间内的就不在选择其中出去。比如说我规定不能早于2018-05-20，那么我选在了2018后，5月之前的月份1234都不出现，只有564789....，同理我选在了2018-05，那么20号之前的日期也不出现。
这仅仅是建议，不管如果都多谢大神的分享。比心

**Comment by xiaosong520** [comment]
@qianshengta 年月日的时间限制已经支持了的，可以参考demo工程或者wiki文档~

**Comment by qianshengta** [comment]
@xiaosong520  您说的是不是通过设置开始和结束时间来限制，而不是我理解的直接通过一个方法来设置限制时间？

**Comment by qianshengta** [comment]
的确是如我所说通过设置开始和结束日期来限制，只是一开始我设置了可循环，看上去好像没限制了一样
