### ISSUE TITLE
建议把gradle里的compile改成implementation

### ISSUE THREAD

**Issue by KevinLee089** [Bigkoo/Android-PickerView#667]
compile关键字将在2018年底移除，现在PickerView中依赖WheelView还是使用的compile关键字，导入到项目中则会有提示：Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
但是个人项目中是没有任何使用compile关键字的地方。

**Comment by xiaosong520** [comment]
@KevinLee089 项目gradle 版本暂未升级，年底会抽时间升级一下。
