### ISSUE TITLE
若TimePick已经初始化了，想再从新show之前，从新设置时间，但是好像没有方法！

### ISSUE THREAD

**Issue by LLQQHH** [Bigkoo/Android-PickerView#700]

**Comment by LLQQHH** [comment]
TimePick没有设SetDate，是TimePickerBuild才有，但是我已经初始化过Timepicker了，不能再去用Buiid.build();

**Comment by xiaosong520** [comment]
@LLQQHH TimePickerView 里面是有setDate 方法的，建议确认一下哦~

**Comment by LLQQHH** [comment]
不好意思看到了
