### ISSUE TITLE
时间范围限制不支持时分秒  要是能加上就好了 

### ISSUE THREAD

**Issue by hy20160705** [Bigkoo/Android-PickerView#702]
Class：WheelTime 
public void setRangDate(Calendar startDate, Calendar endDate) {

        if (startDate == null && endDate != null) {
            int year = endDate.get(Calendar.YEAR);
            int month = endDate.get(Calendar.MONTH) + 1;
            int day = endDate.get(Calendar.DAY_OF_MONTH);
            if (year > startYear) {
                this.endYear = year;
                this.endMonth = month;
                this.endDay = day;
            } else if (year == startYear) {
                if (month > startMonth) {
                    this.endYear = year;
                    this.endMonth = month;
                    this.endDay = day;
                } else if (month == startMonth) {
                    if (day > startDay) {
                        this.endYear = year;
                        this.endMonth = month;
                        this.endDay = day;
                    }
                }
            }

        } else if (startDate != null && endDate == null) {
            int year = startDate.get(Calendar.YEAR);
            int month = startDate.get(Calendar.MONTH) + 1;
            int day = startDate.get(Calendar.DAY_OF_MONTH);
            if (year < endYear) {
                this.startMonth = month;
                this.startDay = day;
                this.startYear = year;
            } else if (year == endYear) {
                if (month < endMonth) {
                    this.startMonth = month;
                    this.startDay = day;
                    this.startYear = year;
                } else if (month == endMonth) {
                    if (day < endDay) {
                        this.startMonth = month;
                        this.startDay = day;
                        this.startYear = year;
                    }
                }
            }

        } else if (startDate != null && endDate != null) {
            this.startYear = startDate.get(Calendar.YEAR);
            this.endYear = endDate.get(Calendar.YEAR);
            this.startMonth = startDate.get(Calendar.MONTH) + 1;
            this.endMonth = endDate.get(Calendar.MONTH) + 1;
            this.startDay = startDate.get(Calendar.DAY_OF_MONTH);
            this.endDay = endDate.get(Calendar.DAY_OF_MONTH);

        }

    }

**Comment by hy20160705** [comment]
如果我只改WheelTime中的这个方法 可以生效吗 当前版本是3.2.7

**Comment by xiaosong520** [comment]
@hy20160705 理论上可以，但是逻辑很复杂，判断的嵌套层级太深。

**Comment by hy20160705** [comment]
也就是光改这里的逻辑是行不通的是吧 
我看了一下issue的问题 还是有很多人都有这个诉求 如果有时间和精力的话 建议把这个功能加一下

**Comment by xiaosong520** [comment]
@hy20160705 上面贴的代码块只是对初始化设置的时间取值范围做限制。时间选择器联动的逻辑在WheelTime类的 setSolar和 setLunar 方法里。要支持年月日时分秒的话联动限制的话，六级嵌套监听逻辑及数据处理会很复杂。

**Comment by DubheBroken** [comment]
@xiaosong520 不需要六级嵌套监听，每天的时分秒都是一样的，可以把时分秒和年月日分开做。年月日三级联动，时分秒互不干涉。

**Comment by sweet-guy** [comment]
有好的解决办法么

**Comment by sinduanan** [comment]
希望能请提供个可以截止到时分秒的方法。
