### ISSUE TITLE
自定义时间选择器，仿滴滴出行时间选择控件交互效果

### ISSUE THREAD

**Issue by shareBusfor** [Bigkoo/Android-PickerView#705]
![default](https://user-images.githubusercontent.com/38179236/50619870-fc79c480-0f36-11e9-92db-3e844411bf1e.gif)
自定义时间选择器，仿滴滴出行选择出发时间控件交互效果。

**Comment by shareBusfor** [comment]
@xiaosong520 还要修改部分源码才可以，我是用了联动的。

**Comment by a2203611** [comment]
@shareBusfor  有源码吗 朋友

**Comment by 158037497** [comment]
你好能分享下吗

**Comment by shareBusfor** [comment]
@a2203611 @158037497 
最近才看到你们的回复。我是基于作者源码进行了部分修改，修改内容主要在：WheelOptions.java文件，然后就是数据源的自定义，我这边提供我的model文件。
首先贴出我修改的WheelOptions部分代码：
`   
    private boolean isFromFirstLine = true; //是否是从第一列第一行滚动过来的
    private boolean isFromDayHourFirstLine = true;  //是否是从第二列第一行滚动过来的
    /**
     * 仿滴滴出行时间联动选择器
     * @param options1Items
     * @param options2Items
     * @param options3Items
     */
    public void setSelectPicker(List<T> options1Items,
                                List<List<T>> options2Items,
                                List<List<List<T>>> options3Items){
        this.mOptions1Items = options1Items;
        this.mOptions2Items = options2Items;
        this.mOptions3Items = options3Items;

        // 选项1
        wv_option1.setAdapter(new ArrayWheelAdapter(mOptions1Items));
        wv_option1.setCurrentItem(0);
        // 选项2
        if (mOptions2Items != null) {
            wv_option2.setAdapter(new ArrayWheelAdapter(mOptions2Items.get(0)));
        }
        wv_option2.setCurrentItem(wv_option2.getCurrentItem());
        // 选项3
        if (mOptions3Items != null) {
            wv_option3.setAdapter(new ArrayWheelAdapter(mOptions3Items.get(0).get(0)));
        }

        wv_option3.setCurrentItem(wv_option3.getCurrentItem());
        wv_option1.setIsOptions(true);
        wv_option2.setIsOptions(true);
        wv_option3.setIsOptions(true);

        if (this.mOptions2Items == null) {
            wv_option2.setVisibility(View.GONE);
        } else {
            wv_option2.setVisibility(View.VISIBLE);
        }
        if (this.mOptions3Items == null) {
            wv_option3.setVisibility(View.GONE);
        } else {
            wv_option3.setVisibility(View.VISIBLE);
        }

        // 联动监听器
        wheelListener_option1 = new OnItemSelectedListener() {

            @Override
            public void onItemSelected(int index) {
                int opt2Select = 0;

                if (index == 0){
                    isFromFirstLine = true;
                    String currentHour = (String) mOptions2Items.get(1).get(wv_option2.getCurrentItem());
                    wv_option2.setAdapter(new ArrayWheelAdapter(mOptions2Items.get(0)));
                    opt2Select = mOptions2Items.get(0).indexOf(currentHour);
                    Log.d("WheelOptions","current Op2Select is:"+opt2Select);

                    if (opt2Select == -1){
                        opt2Select = 0;
                        wv_option2.setCurrentItem(opt2Select);
                    }else {
                        wv_option2.setCurrentItem(opt2Select);
                    }

                }else {
                    int itemCount = wv_option2.getItemsCount();
                    //多列同时滚动的时候，可能出现第二列的数据源混乱问题，需要重新设置数据源以及选中项
                    //如果是首次从首行滚动过来的，需要重新设置数据源以及选中项
                    if (isFromFirstLine || itemCount == mOptions2Items.get(0).size() ){
//                        isFromFirstLine = false;
                        String currentHour = (String) mOptions2Items.get(0).get(wv_option2.getCurrentItem());
                        wv_option2.setAdapter(new ArrayWheelAdapter(mOptions2Items.get(1)));
                        opt2Select = mOptions2Items.get(1).indexOf(currentHour);
                        wv_option2.setCurrentItem(opt2Select);
                    }
                }
                wheelListener_option2.onItemSelected(opt2Select);

            }
        };

        wheelListener_option2 = new OnItemSelectedListener() {

            @Override
            public void onItemSelected(int index) {

                int opt1Select = wv_option1.getCurrentItem();
                int opt3Select;
                if (opt1Select == 0){

                    if (index == 0){
                        isFromDayHourFirstLine = true;
                        //获取滚动前选中的minute
                        String currentMinute = (String) mOptions3Items.get(1).get(0).get(wv_option3.getCurrentItem());
                        wv_option3.setAdapter(new ArrayWheelAdapter(mOptions3Items.get(0).get(0)));
                        //计算新的minute的选中位置
                        if (mOptions3Items.get(0).get(0).contains(currentMinute)){
                            opt3Select = mOptions3Items.get(0).get(0).indexOf(currentMinute);
                        }else {
                            opt3Select = 0;
                        }
                        Log.d("WheelOptions","opt3select is:"+opt3Select);
                        wv_option3.setCurrentItem(opt3Select);
                    }else {
                        if (isFromDayHourFirstLine){
                            isFromDayHourFirstLine = false;
                            int itemCount = wv_option3.getItemsCount();
                            String currentMinute;
                            if (itemCount == mOptions3Items.get(0).get(0).size()){
                                currentMinute = (String) mOptions3Items.get(0).get(0).get(wv_option3.getCurrentItem());
                            }else {
                                currentMinute = (String) mOptions3Items.get(1).get(0).get(wv_option3.getCurrentItem());
                            }
                            wv_option3.setAdapter(new ArrayWheelAdapter(mOptions3Items.get(1).get(0)));
                            opt3Select = mOptions3Items.get(1).get(0).indexOf(currentMinute);
                            wv_option3.setCurrentItem(opt3Select);
                        }


                    }
                }else {
                    //如果是从第一列滚动过来的，重新设置数据源与选中项
                    if (isFromFirstLine){
                        isFromFirstLine = false;
                        String currentMinute;
                        int itemCount = wv_option3.getItemsCount();
                        if (itemCount == mOptions3Items.get(0).get(0).size()){
                            currentMinute = (String) mOptions3Items.get(0).get(0).get(wv_option3.getCurrentItem());
                        }else {
                            currentMinute = (String) mOptions3Items.get(1).get(0).get(wv_option3.getCurrentItem());
                        }
                        wv_option3.setAdapter(new ArrayWheelAdapter(mOptions3Items.get(1).get(0)));
                        opt3Select = mOptions3Items.get(1).get(0).indexOf(currentMinute);
                        wv_option3.setCurrentItem(opt3Select);
                    }
                }

            }
        };

        // 添加联动监听
        if (options1Items != null && linkage) {
            wv_option1.setOnItemSelectedListener(wheelListener_option1);
        }
        if (options2Items != null && linkage) {
            wv_option2.setOnItemSelectedListener(wheelListener_option2);
        }
        if (options3Items != null && linkage && optionsSelectChangeListener != null) {
            wv_option3.setOnItemSelectedListener(new OnItemSelectedListener() {
                @Override
                public void onItemSelected(int index) {
                    optionsSelectChangeListener.onOptionsSelectChanged(wv_option1.getCurrentItem(), wv_option2.getCurrentItem(), index);
                }
            });
        }
    }`

然后下面是我的相应的数据Model文件：DateTimeModel.java
`/**
 * 创建时间： 2019/01/03 21:29
 * 创建者: 木林
 * 功能描述:
 **/
public class DateTimeModel implements Parcelable {
    /**
     * 日期列表
     */
    private ArrayList<String> dayList;
    /**
     * 这个是我这边有数据关联的第二个选择wheel需要获取的数据
     */
    private ArrayList<String> selectDayList;
    /**
     * 通用的24小时制list
     */
    private ArrayList<String> commonHourList;
    /**
     * 通用的时间list
     */
    private ArrayList<String> commonMinuteList;
    /**
     * 设定的今日开始的时间list
     */
    private ArrayList<String> currentHourList;
    /**
     * 设定的今日开始的那个小时的分钟list
     */
    private ArrayList<String> currentMinuteList;
    private int[] hourMinute;

    public DateTimeModel(){

    }

    protected DateTimeModel(Parcel in) {
        dayList = in.createStringArrayList();
        selectDayList = in.createStringArrayList();
        commonHourList = in.createStringArrayList();
        commonMinuteList = in.createStringArrayList();
        currentHourList = in.createStringArrayList();
        currentMinuteList = in.createStringArrayList();
        hourMinute = in.createIntArray();
    }

    public static final Creator<DateTimeModel> CREATOR = new Creator<DateTimeModel>() {
        @Override
        public DateTimeModel createFromParcel(Parcel in) {
            return new DateTimeModel(in);
        }

        @Override
        public DateTimeModel[] newArray(int size) {
            return new DateTimeModel[size];
        }
    };

    public void setSelectDayList(ArrayList<String> selectDayList) {
        this.selectDayList = selectDayList;
    }

    public ArrayList<String> getSelectDayList() {
        return selectDayList;
    }

    public void setHourMinute(int[] hourMinute) {
        this.hourMinute = hourMinute;
    }

    public int[] getHourMinute() {
        return hourMinute;
    }

    public ArrayList<String> getDayList() {
        return dayList;
    }

    public void setDayList(ArrayList<String> dayList) {
        this.dayList = dayList;
    }

    public ArrayList<String> getCommonHourList() {
        return commonHourList;
    }

    public void setCommonHourList(ArrayList<String> commonHourList) {
        this.commonHourList = commonHourList;
    }

    public ArrayList<String> getCommonMinuteList() {
        return commonMinuteList;
    }

    public void setCommonMinuteList(ArrayList<String> commonMinuteList) {
        this.commonMinuteList = commonMinuteList;
    }

    public ArrayList<String> getCurrentHourList() {
        return currentHourList;
    }

    public void setCurrentHourList(ArrayList<String> currentHourList) {
        this.currentHourList = currentHourList;
    }

    public ArrayList<String> getCurrentMinuteList() {
        return currentMinuteList;
    }

    public void setCurrentMinuteList(ArrayList<String> currentMinuteList) {
        this.currentMinuteList = currentMinuteList;
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeStringList(dayList);
        dest.writeStringList(selectDayList);
        dest.writeStringList(commonHourList);
        dest.writeStringList(commonMinuteList);
        dest.writeStringList(currentHourList);
        dest.writeStringList(currentMinuteList);
        dest.writeIntArray(hourMinute);
    }
}`

时间数据源的设置与获取这一块，根据个人情况自行定义，我这边就不贴我的代码了。
有问题的话，可以发邮件yuyuljf@foxmail,com,我有看到的话会回复的。
年底了，项目比较忙，事情也比较多，可能无法及时回复。

**Comment by shareBusfor** [comment]
[WheelOptions.txt](https://github.com/Bigkoo/Android-PickerView/files/2779255/WheelOptions.txt)
[DateTimeModel.txt](https://github.com/Bigkoo/Android-PickerView/files/2779256/DateTimeModel.txt)

**Comment by shareBusfor** [comment]
回复框里的代码可读性比较差，可以参看上面的txt文件
