### ISSUE TITLE
自定义时间选择器布局，选中监听不回调 

### ISSUE THREAD

**Issue by JhoBor** [Bigkoo/Android-PickerView#731]
参考demo，通过TimePickerBuilder方式自定义布局，滚动选择器，OnTimeSelectListener.onTimeSelect()方法不回调，求解决办法

**Comment by gouladeshi** [comment]
我也遇到了这样的问题 你解决了么

**Comment by 1programmer2dfg3** [comment]
我也是的，咋解决？

**Comment by xiaosong520** [comment]
onTimeSelect 是点击确认按钮才会回调的，若要实时回调，则需要实现setTimeSelectChangeListener

**Comment by xiaosong520** [comment]
@JhoBor  自定义布局需要代码调用 returnData 方法
