### ISSUE TITLE
怎么设置弹出高度

### ISSUE THREAD

**Issue by quert999** [Bigkoo/Android-PickerView#732]
issue里面搜了高度，height等关键字没找到怎么设置。
作者帮忙解答下，因为现在在全面屏手机上显示会显得比较矮。
所以想设置一下高度。

**Comment by ZhouBey** [comment]
我也遇到这个问题了

**Comment by quert999** [comment]
> 我也遇到这个问题了

#722  搜到了，需要设置字体大小和显示item个数来控制。
需要把项目作为module依赖到自己项目中。
修改wheelview类的源码。

**Comment by mrinmoy007roy** [comment]
你能展示样本代码来改变高度吗？

**Comment by bakonMa** [comment]
看了好多都没办法解决整体高度问题，又不想引入module，无奈自己尝试了一下
根本方案还是 需要作者大大可以开方的更完美一些 
作者大大辛苦啦
1：可以解决整体高度问题（需要配合setLineSpacingMultiplier，setItemVisibleCount 呈现最优效果）
2：关于点击标题，和最底部会dismiss的问题 setOnClickListener

1：TimePickerView
timePickerView.dialogContainerLayout.apply {
            findViewById<View>(R.id.timepicker).apply {
                minimumHeight = UIUtils.dp2px(context, 220f)//自己设置高度
            }
            setOnClickListener { }
        }
2:OptionsPickerView
optionsPickerView.dialogContainerLayout.apply {
            findViewById<View>(R.id.optionspicker).apply {
                minimumHeight = UIUtils.dp2px(context, 220f)//自己设置高度
            }
            setOnClickListener { }
        }

**Comment by bakonMa** [comment]
看了好多都没办法解决整体高度问题，又不想引入module，无奈自己尝试了一下
根本方案还是 需要作者大大可以开方的更完美一些
作者大大辛苦啦
1：可以解决整体高度问题（需要配合setLineSpacingMultiplier，setItemVisibleCount 呈现最优效果）
2：关于点击标题，和最底部会dismiss的问题 setOnClickListener
3：设置标题高度（覆盖values.xml中 pickerview_topbar_height 的值）
<dimen name="pickerview_topbar_height">40dp</dimen>

1：TimePickerView
timePickerView.dialogContainerLayout.apply {
findViewById(R.id.timepicker).apply {
minimumHeight = UIUtils.dp2px(context, 220f)//自己设置高度
}
setOnClickListener { }
}
2:OptionsPickerView
optionsPickerView.dialogContainerLayout.apply {
findViewById(R.id.optionspicker).apply {
minimumHeight = UIUtils.dp2px(context, 220f)//自己设置高度
}
setOnClickListener { }
}
