### ISSUE TITLE
studio 3.3.2  gradle 5.0 版本，运行提示找不到IPickerViewData接口

### ISSUE THREAD

**Issue by lizc0512** [Bigkoo/Android-PickerView#735]
相同的代码在studio 3.0.1 gradle 4.4版本上是可以的，正常运行，使用的是最新的4.1.7版本，麻烦坐着能尽快看下，可能需要适配了

**Comment by cultivation-of-taoism** [comment]
的确是这样  我也遇到了Unresolved reference: IPickerViewData

**Comment by lizc0512** [comment]
> 的确是这样 我也遇到了Unresolved reference: IPickerViewData

我现在是3.3.2版本，gradle版本是4.10.1版本，可以使用，gradle再升级就不能用了

**Comment by kydiwen** [comment]
一样的错误，等适配吧

**Comment by daleiyinsi** [comment]
卧槽，我升级到android studio 3.4 引不到这个包，怎么办

**Comment by xiaosong520** [comment]
@daleiyinsi @kydiwen @lizc0512 下个版本会适配

**Comment by txwgoogol** [comment]
有木有临时解决办法 :(

**Comment by svran** [comment]
@daleiyinsi @kydiwen @ @lizc0512 
再多加个引用:     implementation 'com.contrarywind:wheelview:4.0.9' 临时解决一下吧.

**Comment by Masksam** [comment]
> @daleiyinsi @kydiwen @ @lizc0512
> 再多加个引用: implementation 'com.contrarywind:wheelview:4.0.9' 临时解决一下吧.

thank you

**Comment by jhbxyz** [comment]
WheelView 也找不到了 也是gradle到5.0+ 升级的原因    implementation 'com.contrarywind:wheelview:4.0.9' 确实可以临时解决一下

**Comment by MidTse** [comment]
@xiaosong520 可能是gradle高版本中”compile“依赖命令失效导致的，改成”api“应该就没问题了。
![image](https://user-images.githubusercontent.com/11783892/56426655-a402e300-62eb-11e9-809f-47676eac3c21.png)

**Comment by xiaosong520** [comment]
v4.1.8版本已更新，兼容此问题。
