### ISSUE TITLE
老哥，麻烦更新一下4.X文档

### ISSUE THREAD

**Issue by ouerfeiyu** [Bigkoo/Android-PickerView#736]
我在使用TimePickerView的时候，4.X文档的链接点进去还是3.X的文档。尤其是demo代码，许多方法你现在都已经改变了，可能新手想要摸索出正确的使用方法会受阻。
例如，PickerOptions内部属性的注入方式现在是直接用=赋值。
再例如，PickerOptions必须为context属性赋值，否则会报空指针异常。
以下是4.1.7正确使用示例：
![图片](https://user-images.githubusercontent.com/36292231/55467177-515ed100-5633-11e9-93dd-755b3a9ada39.png)

**Comment by SenYuSAMA** [comment]
附议 4.x的文档太多太多错误了。。。

**Comment by xiaosong520** [comment]
@ouerfeiyu  不是直接new TimePickerView 的， 通过TimePickerBuilder  建造出来的哦~~~

**Comment by xiaosong520** [comment]
@SenYuSAMA  感谢指正，已修改
