### ISSUE TITLE
什么时候把compile改为最新的implementation或api，最新的Gradle已经不支持了

### ISSUE THREAD

**Issue by Thor-jelly** [Bigkoo/Android-PickerView#746]
Android Studio3.4
classpath 'com.android.tools.build:gradle:3.4.0'
distributionUrl=https\://services.gradle.org/distributions/gradle-5.1.1-all.zip

Caused by: org.gradle.api.internal.tasks.compile.CompilationFailedException: Compilation failed; see the compiler error output for details.

错误: 无法访问WheelView
找不到com.contrarywind.view.WheelView的类文件

**Comment by smilingK** [comment]
我的临时解决办法是本地

**Comment by xiaosong520** [comment]
@smilingK @Thor-jelly  下个版本会适配

**Comment by ruanbaojun1105** [comment]
所以我还是回到了gradle 4.10.1

**Comment by liangfengxixi** [comment]
gradle 5.1.1的确出问题了，需要自己再引入一个依赖

**Comment by Thor-jelly** [comment]
回复有三种方法：
1.回到原来gradle的版本（我用的这种）
2.移除当前依赖中的compile，在本地引入implementation
3.等新版本
