### ISSUE TITLE
部分手机切换时区后，TimePickerView onTimeSelect时间不对

### ISSUE THREAD

**Issue by ShrimpZhang** [Bigkoo/Android-PickerView#749]
使用过程中发现，部分手机（魅族Pro6、魅族m3、华为荣耀7）手机，在手机切换时区后（-4时区）， onTimeSelect返回的时间比实际点击的少一天。

**Comment by xiaosong520** [comment]
切换时区后应该需要重新设置一下时间数据

**Comment by ShrimpZhang** [comment]
谢谢您的回复，我每车次使用都是有重新设置时区的，大部分手机上表现正常，但是 同事的魅族pro6,华为荣耀7 切换手机时区却不行，这个是否和手机系统有关系呢？由于MyApplication没有重新 onCreate？




------------------ 原始邮件 ------------------
发件人: "xiaosongzeem"<notifications@github.com>;
发送时间: 2019年4月24日(星期三) 下午2:13
收件人: "Bigkoo/Android-PickerView"<Android-PickerView@noreply.github.com>;
抄送: "zhangmn"<879417562@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [Bigkoo/Android-PickerView] 部分手机切换时区后，TimePickerView onTimeSelect时间不对 (#749)




切换时区后应该需要重新设置一下时间数据

**Comment by zhujunhua2012** [comment]
WheelTime.dateFormat = SimpleDateFormat("yyyy-MM-dd HH:mm:ss")

**Comment by ShrimpZhang** [comment]
学习了，谢谢作者大大
