### ISSUE TITLE
提个意见

### ISSUE THREAD

**Issue by githubzjh** [Bigkoo/Android-PickerView#773]
能不能把mPickerOptions.decorview不要固定为所在Activity窗口的decorview（可以设成默认的），整成动态的，用户想放在那里就放在那里，未指明使用默认窗口的Decorview中，否则放在用户指定的ViewGroup中

**Comment by githubzjh** [comment]
增加灵活性嘛，拓展性嘛

**Comment by xiaosong520** [comment]
@githubzjh 已有提供了方法去设置

**Comment by xiaosong520** [comment]
@githubzjh 可参考wiki api 文档

**Comment by githubzjh** [comment]
@xiaosong520 是吗？，能否直接发一下那个方法名以及所在的类，我看源码是没有这个功能

**Comment by githubzjh** [comment]
@xiaosong520 我说的不是自定义布局啊，我说的最顶层的父容器不要固定为activity所在的decorview，

**Comment by xiaosong520** [comment]
@githubzjh  setDecorView 方法可以设置的，demo工程以及 wiki 和issue 区都已经有提示了的
