### ISSUE TITLE
求作者开放WhellView设置可见条数的方法

### ISSUE THREAD

**Issue by xzwzyf0503** [Bigkoo/Android-PickerView#779]

**Comment by hongyanfengzi** [comment]
十分需要, 开始时间的 时分秒,均不可控制, 会选到小于开始时间的值,  不符合逻辑

**Comment by lxt1994** [comment]
调用setLineSpacingMultiplier(float f)即可

**Comment by xzwzyf0503** [comment]
作者你好，感谢你的来信。
setLineSpacingMultiplier(float f)是调整行间距的，而非显示行数，
当前视图显示的行数是9（itemsVisible = 11）过多，我们在开发中重写改成了5行（itemsVisible=7），
所以希望您的空间增加方法 控制itemsVisible的值，很多开发者也遇到了同样的需求。




------------------ 原始邮件 ------------------
发件人: "LiXiaoTong"<notifications@github.com>;
发送时间: 2019年7月31日(星期三) 上午9:48
收件人: "Bigkoo/Android-PickerView"<Android-PickerView@noreply.github.com>;
抄送: "zyf"<385253067@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [Bigkoo/Android-PickerView] 求作者开放WhellView设置可见条数的方法 (#779)




调用setLineSpacingMultiplier(float f)即可

**Comment by xiaosong520** [comment]
@xzwzyf0503 @hongyanfengzi supported in version 4.1.9
