### ISSUE TITLE
自己在时间选择器里新加了一个WheelView后，与原来的WheelView没有对齐

### ISSUE THREAD

**Issue by ygeng** [Bigkoo/Android-PickerView#782]
如图，这个偏差跟机型还有关
![image](https://user-images.githubusercontent.com/13791355/60495857-33f9db80-9ce4-11e9-93fe-e024722077c6.png)

**Comment by xiaosong520** [comment]
@ygeng 用的是哪个版本？

**Comment by ygeng** [comment]
@xiaosong520 4.1.8

**Comment by xiaosong520** [comment]
@ygeng  setLineSpacingMultiplier  看下这个方法是否设置的一致。

**Comment by ygeng** [comment]
![image](https://user-images.githubusercontent.com/13791355/60573672-afbe5b80-9daa-11e9-8bc7-a7f198c44f90.png)

@xiaosong520 是一致的

**Comment by ygeng** [comment]
@xiaosong520 你好，请问有解决方案吗？

**Comment by xiaosong520** [comment]
@ygeng  建议打印一下 wheelview 里面分隔线的值，看样子像是itemHeight 不一致。

**Comment by ygeng** [comment]
@xiaosong520 你好，itemHeight打印了是一致的，高度应该是一致的，就是新加的跟原来的错开了

**Comment by xiaosong520** [comment]
@ygeng  分割线的 Y值呢？
