### ISSUE TITLE
自定义布局，时间选择监听不回调

### ISSUE THREAD

**Issue by gouladeshi** [Bigkoo/Android-PickerView#788]
参考demo，通过TimePickerBuilder方式自定义布局，滚动选择器，OnTimeSelectListener.onTimeSelect()方法不回调，求解决办法

**Comment by RaoKui** [comment]
稍微看看源码就知道了，你手动调用  mDatePickView.returnData(); 就能回调

**Comment by gouladeshi** [comment]
> 稍微看看源码就知道了，你手动调用 mDatePickView.returnData(); 就能回调
嗯嗯 是我自己的问题 我自己又看了一遍源码，当时只是用简单的commit 没有看到这个returnData 
谢谢啦

**Comment by KunMinX** [comment]
@gouladeshi 
这个接口名称设计得不好。
你要的效果，在 这个接口里：
.setTimeSelectChangeListener(new OnTimeSelectChangeListener() {
                    @Override
                    public void onTimeSelectChanged(Date date) {
                        Log.i("pvTime", "onTimeSelectChanged");
                    }
                })
