### ISSUE TITLE
关于PopupWindow上弹出PickerView问题#279回答的不是很理解

### ISSUE THREAD

**Issue by shineqstm** [Bigkoo/Android-PickerView#815]
问题还是[#279 ](url)描述的那样，pickerview 在PopupWindow底层，关于回答

> @gitzgq 3.2.5版本已经支持自定义设置控件的父容器了，通过setDecorView方法把Popupwindow 的id 传入即可解决被遮挡的问题。
这个Popupwindow 的id 传入  如何传入，能否有个示例代码

**Comment by shineqstm** [comment]
用了 中文说明文档（4.x版）的8.Dialog模式 实现了从底下弹出效果

**Comment by longcaiyinyuan** [comment]
BasePopupWindow  弹出pickerview 被遮挡 解决方法
.setDecorView((ViewGroup) getPopupWindow().getContentView().getRootView()) 
<img width="1212" alt="WX20220324-114253@2x" src="https://user-images.githubusercontent.com/44362109/159837894-f3fbe0d4-0bd8-46b5-99b3-556a0ad0c07a.png">
![2891648093494_ pic](https://user-images.githubusercontent.com/44362109/159838050-28ff0d06-6824-465b-ac65-9964552d5b97.jpg)
