### ISSUE TITLE
怎么取消点击内容以外的地方会关闭界面

### ISSUE THREAD

**Issue by LinJunhao** [Bigkoo/Android-PickerView#829]
我设置了自定义PickerView是一个dialog并且点击外部不可取消，因为我希望用户点击返回按钮才能取消dialog，但是当我点击dialog中pickerview内容以外的背景会取消这个dialog。

查看源码后我发现了这样一段代码：
```
//给背景设置点击事件,这样当点击内容以外的地方会关闭界面
dialogView.setOnClickListener(new View.OnClickListener() {
    @Override
     public void onClick(View view) {
        dismiss();
    }
});
```

有什么办法可以取消这个点击事件吗？

**Comment by threedeer** [comment]
请问怎么解决这个问题的

**Comment by JonsonHao** [comment]
> 请问怎么解决这个问题的

在源码中找到我上面那段代码，然后把这个点击事件删了就行了
