### ISSUE TITLE
月日联动有问题，求解决

### ISSUE THREAD

**Issue by ixiangfeng** [Bigkoo/Android-PickerView#86]
同时滑动月和日，停下来后单独滑动月，日会跳动，例如同时滑动停下来后1月20日，单独把月滑动到2、3、4、5、6等，日会自己跳到22、20、21、20、21，如多次同时滑动月日，则跳动更大，是联动监听出的问题吗

**Comment by ixiangfeng** [comment]
设置不能循环时不会出现这问题

**Comment by keluokeda** [comment]
我这里测试的结果是：在pvTime.setCyclic(true)的情况下，月份从大月（31天）滑动到小月（30天），日会+1，小月滑动到大月，日会-1 @ixiangfeng
