### ISSUE TITLE
4.1.9 设置range日期选择异常

### ISSUE THREAD

**Issue by charmeleon2** [Bigkoo/Android-PickerView#875]
`  val current = Calendar.getInstance()
        var mBirth = tv_birth.text.toString()
        mBirth="1996-02-03"
        LogUtils.w(mBirth)
        if (mBirth.isBlank()) {
            current[Calendar.YEAR] -= 24
        } else {
            current[Calendar.YEAR] = mBirth.substring(0, 4).toInt()
            current[Calendar.MONTH] = mBirth.substring(5, 7).toInt() - 1
            current[Calendar.DAY_OF_MONTH] = mBirth.substring(8, 10).toInt()
            LogUtils.w(mBirth.substring(0, 4).toInt(),mBirth.substring(5, 7).toInt() - 1, mBirth.substring(8, 10).toInt())
        }
        val start = Calendar.getInstance()
        start[Calendar.YEAR] -= 60
        val end = Calendar.getInstance()
        end[Calendar.YEAR] -= 18
        val listener =
                OnTimeSelectListener { date, _ ->
                    LogUtils.w(date)
                    mBirth = SimpleDateFormat("yyyy-MM-dd", Locale.CHINA).format(date)
                    tv_birth.text = mBirth
                }
        val picker = TimePickerBuilder(this, listener)
                .setType(booleanArrayOf(true, true, true, false, false, false))
                .setDate(current)
                .setRangDate(start, end)
                .setCancelText(getString(R.string.cancel))
                .setSubmitText(getString(R.string.determine))
                .setTitleSize(14)
                .setContentTextSize(14)
                .setSubCalSize(14)
                .setLineSpacingMultiplier(2.75f)
                .build()
        picker.show()`
这样一段代码，在4.1.9版本上，日期会从16号开始，1-15丢失（改成2月以外的月份没有这问题，或者去掉range限制，也是正常的），4.1.8版本没有这问题，

**Comment by zzw3239** [comment]
同样遇到这个问题，丢失的日期与起始日期有关，只要不是从1日开始，都会对应缺失。
