### ISSUE TITLE
请问时间选择器怎么把起始项自定义如图这样。

### ISSUE THREAD

**Issue by chaoyang-zhou** [Bigkoo/Android-PickerView#951]
<img width="209" alt="截屏2020-11-10 下午1 50 18" src="https://user-images.githubusercontent.com/62043326/98633079-adcfb980-235b-11eb-8d74-5edb0f282f13.png">
第一个选择，自定义中文选项，请问可以定义吗？

**Comment by chaoyang-zhou** [comment]
https://github.com/Bigkoo/Android-PickerView/blob/master/app/src/main/res/layout/pickerview_custom_time.xml

**Comment by MikeVoy** [comment]
> https://github.com/Bigkoo/Android-PickerView/blob/master/app/src/main/res/layout/pickerview_custom_time.xml

老哥请问你这边月份和天数的滚轮是怎么合并的啊

**Comment by DalesDawson** [comment]
月日合并怎么搞的，老哥

**Comment by DalesDawson** [comment]
> > https://github.com/Bigkoo/Android-PickerView/blob/master/app/src/main/res/layout/pickerview_custom_time.xml
> 
> 老哥请问你这边月份和天数的滚轮是怎么合并的啊

你后来实现了嘛
