### ISSUE TITLE
WheelView不能单独设置center的字体为加粗

### ISSUE THREAD

**Issue by Slovenl** [Bigkoo/Android-PickerView#963]

**Comment by Slovenl** [comment]
现使用反射可以单独设置中间区域和边缘区域的样式

**Comment by Slovenl** [comment]
~

**Comment by guochuanpei** [comment]
你好  能不能具体的说下思路  或者方便的话把代码贴出来参考下

**Comment by guochuanpei** [comment]
通过反射拿到WheelView类里面的paintCenterText和paintOuterText变量就可以改变字体粗细还有字体样式了
`private void getField(WheelView wheelView) {
        try {
            Field centerText = wheelView.getClass().getDeclaredField("paintCenterText");
            Field outerText = wheelView.getClass().getDeclaredField("paintOuterText");
            centerText.setAccessible(true);
            outerText.setAccessible(true);
            Paint paintCenterText = (Paint) centerText.get(wheelView);
            Paint paintOuterText = (Paint) outerText.get(wheelView);
            if (paintCenterText != null) {
                paintCenterText.setFakeBoldText(true);
            }
            if (paintOuterText != null) {
                paintOuterText.setFakeBoldText(true);
            }
            if (paintCenterText != null) {
                paintCenterText.setTypeface(Typeface.DEFAULT);
            }
            if (paintOuterText != null) {
                paintOuterText.setTypeface(Typeface.DEFAULT);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }`

**Comment by guochuanpei** [comment]
通过反射拿到WheelView类里面的paintCenterText和paintOuterText变量就可以改变字体粗细还有字体样式了
``` java
private void getField(WheelView wheelView) {
        try {
            Field centerText = wheelView.getClass().getDeclaredField("paintCenterText");
            Field outerText = wheelView.getClass().getDeclaredField("paintOuterText");
            centerText.setAccessible(true);
            outerText.setAccessible(true);
            Paint paintCenterText = (Paint) centerText.get(wheelView);
            Paint paintOuterText = (Paint) outerText.get(wheelView);
            if (paintCenterText != null) {
                paintCenterText.setFakeBoldText(true);
            }
            if (paintOuterText != null) {
                paintOuterText.setFakeBoldText(true);
            }
            if (paintCenterText != null) {
                paintCenterText.setTypeface(Typeface.DEFAULT);
            }
            if (paintOuterText != null) {
                paintOuterText.setTypeface(Typeface.DEFAULT);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    } 
```

**Comment by HeyBean-X** [comment]
为啥我反射也没有效果？

**Comment by slovenl** [comment]
来信已受到，祝您心情愉快！
